"use strict";

window.CHARACTER_COMPONENT_MODULES = [
  {
    id: "foundations",
    title: "How character clues work",
    description: "Learn what components do before using them to infer meaning.",
    lessons: [
      {
        id: "meaning-and-sound",
        component: "形声",
        variants: ["meaning clue", "sound clue"],
        name: "Meaning and sound clues",
        cue: "One part often suggests a meaning category while another hints at sound.",
        summary: "Read a character as a system of clues instead of a picture with one fixed story.",
        reliability: "The meaning clue usually narrows a category, not an exact definition. The sound clue may be exact, approximate, or preserved from an older pronunciation.",
        examples: [
          { character: "清", pinyin: "qīng", meaning: "clear; clean", semantic: "氵", semanticNote: "water or liquid", phonetic: "青", phoneticNote: "qīng sound family", insight: "The water clue points toward cleanness or clarity; 青 supplies the modern sound." },
          { character: "请", pinyin: "qǐng", meaning: "to ask; please", semantic: "讠", semanticNote: "speech or language", phonetic: "青", phoneticNote: "qīng sound family", insight: "The speech clue narrows the meaning to something done with words." },
          { character: "情", pinyin: "qíng", meaning: "feeling; emotion", semantic: "忄", semanticNote: "heart or mind", phonetic: "青", phoneticNote: "qīng sound family", insight: "The heart clue points toward feelings while 青 keeps the syllable family recognizable." },
        ],
        questions: [
          { id: "meaning-and-sound-1", character: "清", pinyin: "qīng", prompt: "Which part is the meaning clue in 清?", options: ["氵", "青", "Both parts mean clear", "Neither part"], answer: "氵", meaning: "clear; clean", decomposition: "氵 (water) + 青 (sound)", explanation: "氵 suggests water, liquid, washing, or clarity. 青 supplies the sound clue." },
          { id: "meaning-and-sound-2", character: "情", pinyin: "qíng", prompt: "Without knowing 情, what is the most useful first guess?", options: ["A feeling or mental state", "A kind of metal", "A road or journey", "A plant"], answer: "A feeling or mental state", meaning: "feeling; emotion", decomposition: "忄 (heart/mind) + 青 (sound)", explanation: "忄 narrows the semantic field to feelings and mental states. It does not reveal the exact word by itself." },
          { id: "meaning-and-sound-3", character: "请", pinyin: "qǐng", prompt: "Why can a sound component be only an approximate clue?", options: ["Pronunciations change over time", "Components never carry sound", "Every component has five tones", "The meaning component changes the alphabet"], answer: "Pronunciations change over time", meaning: "to ask; please", decomposition: "讠 (speech) + 青 (sound)", explanation: "Many sound relationships were clearer when the character was created. Modern Mandarin may preserve only part of the original relationship." },
        ],
      },
      {
        id: "component-variants",
        component: "变形",
        variants: ["氵 = 水", "忄/⺗ = 心", "扌 = 手", "灬 = 火"],
        name: "Recognize component variants",
        cue: "A familiar component can change shape when it moves inside a character.",
        summary: "Learn the compressed forms that appear at the left, bottom, or top of a character.",
        reliability: "Position changes shape, but the component can retain the same broad semantic role.",
        examples: [
          { character: "河", pinyin: "hé", meaning: "river", semantic: "氵", semanticNote: "variant of 水", phonetic: "可", phoneticNote: "historical sound clue", insight: "The three dots are the side form of 水 and immediately suggest water." },
          { character: "想", pinyin: "xiǎng", meaning: "to think; to want", semantic: "心", semanticNote: "heart or mind at the bottom", phonetic: "相", phoneticNote: "approximate sound clue", insight: "心 can sit intact at the bottom, while 忄 is its common left-side form." },
          { character: "煮", pinyin: "zhǔ", meaning: "to boil; to cook", semantic: "灬", semanticNote: "bottom form associated with 火", phonetic: "者", phoneticNote: "approximate sound clue", insight: "The four dots at the bottom often point toward fire, heat, or cooking." },
        ],
        questions: [
          { id: "component-variants-1", character: "湖", pinyin: "hú", prompt: "Which full component does 氵 represent?", options: ["水", "木", "手", "言"], answer: "水", meaning: "lake", decomposition: "氵 (water) + 胡 (sound)", explanation: "氵 is the compressed left-side form of 水." },
          { id: "component-variants-2", character: "快", pinyin: "kuài", prompt: "The left side 忄 is a variant of which component?", options: ["心", "火", "口", "人"], answer: "心", meaning: "fast; happy", decomposition: "忄 (heart/mind) + 夬 (sound)", explanation: "忄 is the left-side form of 心 and often marks feelings or mental states." },
          { id: "component-variants-3", character: "煮", pinyin: "zhǔ", prompt: "What broad category does 灬 suggest here?", options: ["Heat or cooking", "Speech", "Travel", "Metal"], answer: "Heat or cooking", meaning: "to boil; to cook", decomposition: "者 (sound) + 灬 (fire/heat)", explanation: "At the bottom of many characters, 灬 is associated with fire and heat." },
        ],
      },
    ],
  },
  {
    id: "people-and-actions",
    title: "People, speech, and action",
    description: "Use body and behavior components to identify human meanings.",
    lessons: [
      {
        id: "person-component",
        component: "亻",
        variants: ["人"],
        name: "People and human roles",
        cue: "people, roles, relationships, or human behavior",
        summary: "亻 is the left-side form of 人 and often places a character in the human world.",
        reliability: "Useful for identifying people and social roles, but it rarely gives the exact relationship or action.",
        examples: [
          { character: "伴", pinyin: "bàn", meaning: "companion; partner", semantic: "亻", semanticNote: "person", phonetic: "半", phoneticNote: "bàn sound clue", insight: "The person clue makes a human relationship a strong first guess." },
          { character: "住", pinyin: "zhù", meaning: "to live; to stay", semantic: "亻", semanticNote: "person", phonetic: "主", phoneticNote: "approximate sound clue", insight: "The character describes what a person does in a place." },
          { character: "伙", pinyin: "huǒ", meaning: "companion; group", semantic: "亻", semanticNote: "person", phonetic: "火", phoneticNote: "huǒ sound clue", insight: "亻 points to people; 火 supplies the modern sound." },
        ],
        questions: [
          { id: "person-component-1", character: "侍", pinyin: "shì", prompt: "What is the best first meaning category for 侍?", options: ["A person or human role", "Water or liquid", "A plant", "A metal object"], answer: "A person or human role", meaning: "to attend on; to serve", decomposition: "亻 (person) + 寺 (sound)", explanation: "亻 makes a person, role, or human action the strongest first hypothesis." },
          { id: "person-component-2", character: "伴", pinyin: "bàn", prompt: "Which part supplies the meaning clue in 伴?", options: ["亻", "半", "Both mean companion", "The final stroke"], answer: "亻", meaning: "companion; partner", decomposition: "亻 (person) + 半 (sound)", explanation: "亻 places the character in the category of people and relationships." },
          { id: "person-component-3", character: "们", pinyin: "men", prompt: "Which interpretation best fits the person clue in 们?", options: ["A marker used with people", "A kind of door", "A river", "A cooking method"], answer: "A marker used with people", meaning: "plural marker for pronouns and some people nouns", decomposition: "亻 (person) + 门 (sound)", explanation: "亻 helps distinguish the grammatical people marker 们 from the independent character 门, door." },
        ],
      },
      {
        id: "mouth-component",
        component: "口",
        variants: [],
        name: "Mouth, voice, and eating",
        cue: "mouth actions, voice, taste, or openings",
        summary: "口 often points toward something done with the mouth or produced by the voice.",
        reliability: "The clue covers a broad field: speaking, singing, eating, tasting, breathing, and openings.",
        examples: [
          { character: "唱", pinyin: "chàng", meaning: "to sing", semantic: "口", semanticNote: "mouth or voice", phonetic: "昌", phoneticNote: "approximate sound clue", insight: "Singing is a mouth and voice action." },
          { character: "喝", pinyin: "hē", meaning: "to drink", semantic: "口", semanticNote: "mouth action", phonetic: "曷", phoneticNote: "historical sound clue", insight: "The exact action is not shown, but the mouth category is useful." },
          { character: "喊", pinyin: "hǎn", meaning: "to shout", semantic: "口", semanticNote: "voice", phonetic: "咸", phoneticNote: "approximate sound clue", insight: "The mouth clue makes a vocal action likely." },
        ],
        questions: [
          { id: "mouth-component-1", character: "咬", pinyin: "yǎo", prompt: "What broad action is most likely for 咬?", options: ["An action of the mouth", "A hand movement", "A metal object", "A road"], answer: "An action of the mouth", meaning: "to bite", decomposition: "口 (mouth) + 交 (sound)", explanation: "口 suggests an action performed with the mouth; here it is biting." },
          { id: "mouth-component-2", character: "味", pinyin: "wèi", prompt: "Which meaning best matches the 口 clue in 味?", options: ["Taste or flavor", "Forest", "Distance", "Emotion"], answer: "Taste or flavor", meaning: "taste; flavor", decomposition: "口 (mouth) + 未 (sound)", explanation: "Taste belongs to the mouth-related semantic field." },
          { id: "mouth-component-3", character: "唱", pinyin: "chàng", prompt: "Which component tells you that 唱 involves voice?", options: ["口", "昌", "日", "Both 日 components"], answer: "口", meaning: "to sing", decomposition: "口 (mouth/voice) + 昌 (sound)", explanation: "口 supplies the broad meaning category; 昌 primarily supplies a sound clue." },
        ],
      },
      {
        id: "heart-component",
        component: "忄",
        variants: ["心", "⺗"],
        name: "Feelings and mental states",
        cue: "emotion, intention, thought, or state of mind",
        summary: "The heart component links many characters to feelings and inner states.",
        reliability: "心-based forms are strong category clues, but modern meanings can be abstract or extended.",
        examples: [
          { character: "情", pinyin: "qíng", meaning: "feeling; emotion", semantic: "忄", semanticNote: "heart or mind", phonetic: "青", phoneticNote: "qīng sound family", insight: "The left side supplies the emotional category." },
          { character: "怕", pinyin: "pà", meaning: "to fear", semantic: "忄", semanticNote: "emotion", phonetic: "白", phoneticNote: "historical sound clue", insight: "Fear is an internal emotional state." },
          { character: "忙", pinyin: "máng", meaning: "busy", semantic: "忄", semanticNote: "mental state", phonetic: "亡", phoneticNote: "approximate sound clue", insight: "Busy describes a state of mind and activity." },
        ],
        questions: [
          { id: "heart-component-1", character: "恨", pinyin: "hèn", prompt: "What category is the best first guess for 恨?", options: ["A feeling", "A liquid", "A plant", "A tool"], answer: "A feeling", meaning: "to hate; hatred", decomposition: "忄 (heart/mind) + 艮 (sound)", explanation: "忄 strongly points toward emotion or a mental state." },
          { id: "heart-component-2", character: "想", pinyin: "xiǎng", prompt: "Where is the heart/mind clue in 想?", options: ["心 at the bottom", "相 at the top", "木 on the left", "目 on the right"], answer: "心 at the bottom", meaning: "to think; to want", decomposition: "相 (sound) + 心 (heart/mind)", explanation: "The full form 心 appears at the bottom and supplies the mental meaning clue." },
          { id: "heart-component-3", character: "愉", pinyin: "yú", prompt: "Which meaning is most plausible from 忄?", options: ["A pleasant feeling", "A copper object", "A route", "A kind of tree"], answer: "A pleasant feeling", meaning: "pleased; cheerful", decomposition: "忄 (heart/mind) + 俞 (sound)", explanation: "The component does not reveal 'pleasant' exactly, but it makes a feeling likely." },
        ],
      },
      {
        id: "hand-component",
        component: "扌",
        variants: ["手"],
        name: "Hand actions",
        cue: "physical actions, handling, contact, or control",
        summary: "扌 is the side form of 手 and frequently marks actions done with the hands.",
        reliability: "Many meanings extend from literal hand movements to abstract actions such as controlling or supporting.",
        examples: [
          { character: "抱", pinyin: "bào", meaning: "to hold; to hug", semantic: "扌", semanticNote: "hand action", phonetic: "包", phoneticNote: "approximate sound clue", insight: "Holding and hugging are direct hand and arm actions." },
          { character: "拍", pinyin: "pāi", meaning: "to pat; to clap; to take a photo", semantic: "扌", semanticNote: "hand action", phonetic: "白", phoneticNote: "historical sound clue", insight: "The older physical action extends to taking a photograph." },
          { character: "推", pinyin: "tuī", meaning: "to push", semantic: "扌", semanticNote: "hand action", phonetic: "隹", phoneticNote: "historical sound clue", insight: "The semantic clue directly matches a physical hand action." },
        ],
        questions: [
          { id: "hand-component-1", character: "按", pinyin: "àn", prompt: "What kind of meaning should 扌 make you test first?", options: ["A hand action", "A spoken phrase", "A feeling", "A plant"], answer: "A hand action", meaning: "to press; to push; according to", decomposition: "扌 (hand) + 安 (sound)", explanation: "Pressing is a direct hand action. The meaning later extends into abstract uses." },
          { id: "hand-component-2", character: "抬", pinyin: "tái", prompt: "Which meaning best fits 抬?", options: ["To lift", "To taste", "To burn", "To travel"], answer: "To lift", meaning: "to lift; to raise", decomposition: "扌 (hand) + 台 (sound)", explanation: "扌 makes a physical action such as lifting the best first hypothesis." },
          { id: "hand-component-3", character: "抱", pinyin: "bào", prompt: "Which part narrows 抱 to an action?", options: ["扌", "包", "勹", "巳"], answer: "扌", meaning: "to hold; to hug", decomposition: "扌 (hand) + 包 (sound)", explanation: "扌 supplies the semantic category; 包 supplies the approximate sound." },
        ],
      },
    ],
  },
  {
    id: "nature-and-materials",
    title: "Nature and materials",
    description: "Identify water, wood, plants, heat, and metal before guessing the exact word.",
    lessons: [
      {
        id: "water-component",
        component: "氵",
        variants: ["水"],
        name: "Water and liquids",
        cue: "water, liquids, washing, flow, or bodies of water",
        summary: "Three dots on the left often place a character in a water-related semantic field.",
        reliability: "The connection may be literal, such as a lake, or extended, such as cleaning and clarity.",
        examples: [
          { character: "河", pinyin: "hé", meaning: "river", semantic: "氵", semanticNote: "water", phonetic: "可", phoneticNote: "historical sound clue", insight: "A river is directly within the water category." },
          { character: "海", pinyin: "hǎi", meaning: "sea", semantic: "氵", semanticNote: "water", phonetic: "每", phoneticNote: "approximate sound clue", insight: "The component identifies a body of water." },
          { character: "洗", pinyin: "xǐ", meaning: "to wash", semantic: "氵", semanticNote: "water or washing", phonetic: "先", phoneticNote: "historical sound clue", insight: "The meaning extends from water to an action performed with water." },
        ],
        questions: [
          { id: "water-component-1", character: "洋", pinyin: "yáng", prompt: "What is the most useful first category for 洋?", options: ["Water or a large body of water", "Speech", "Metal", "Emotion"], answer: "Water or a large body of water", meaning: "ocean; vast; foreign", decomposition: "氵 (water) + 羊 (sound)", explanation: "氵 points toward water. The exact modern meanings extend beyond the literal ocean sense." },
          { id: "water-component-2", character: "泳", pinyin: "yǒng", prompt: "Which meaning best matches the water clue?", options: ["To swim", "To speak", "To hug", "To plant"], answer: "To swim", meaning: "to swim", decomposition: "氵 (water) + 永 (sound)", explanation: "Swimming is an action performed in water." },
          { id: "water-component-3", character: "湖", pinyin: "hú", prompt: "Which component supplies the broad meaning of 湖?", options: ["氵", "胡", "月", "古"], answer: "氵", meaning: "lake", decomposition: "氵 (water) + 胡 (sound)", explanation: "The three-dot water form marks the semantic category." },
        ],
      },
      {
        id: "wood-component",
        component: "木",
        variants: [],
        name: "Wood, trees, and wooden things",
        cue: "trees, wood, parts of plants, or objects traditionally made from wood",
        summary: "木 is useful for recognizing tree parts, timber, and many wooden objects.",
        reliability: "Material clues reflect historical objects, so a modern object may no longer be made from wood.",
        examples: [
          { character: "枝", pinyin: "zhī", meaning: "branch", semantic: "木", semanticNote: "tree or wood", phonetic: "支", phoneticNote: "zhī sound clue", insight: "A branch belongs directly to the tree category." },
          { character: "板", pinyin: "bǎn", meaning: "board; plank", semantic: "木", semanticNote: "wood", phonetic: "反", phoneticNote: "approximate sound clue", insight: "The material clue points toward a wooden board." },
          { character: "桥", pinyin: "qiáo", meaning: "bridge", semantic: "木", semanticNote: "traditional building material", phonetic: "乔", phoneticNote: "qiáo sound clue", insight: "The component preserves the traditional material category." },
        ],
        questions: [
          { id: "wood-component-1", character: "根", pinyin: "gēn", prompt: "What is the strongest first guess from 木?", options: ["A tree or plant part", "A spoken request", "A feeling", "A river"], answer: "A tree or plant part", meaning: "root; basis", decomposition: "木 (tree/wood) + 艮 (sound)", explanation: "The literal meaning is a plant root; abstract meanings such as basis developed from it." },
          { id: "wood-component-2", character: "材", pinyin: "cái", prompt: "Which broad meaning best fits 材?", options: ["Material or timber", "Travel", "Eating", "Emotion"], answer: "Material or timber", meaning: "material; timber; ability", decomposition: "木 (wood) + 才 (sound)", explanation: "木 points toward timber or material, with later abstract extensions." },
          { id: "wood-component-3", character: "枝", pinyin: "zhī", prompt: "Which part is mainly the sound clue in 枝?", options: ["支", "木", "十", "又"], answer: "支", meaning: "branch", decomposition: "木 (tree) + 支 (sound)", explanation: "木 carries the tree meaning while 支 supplies the modern pronunciation." },
        ],
      },
      {
        id: "plant-component",
        component: "艹",
        variants: ["草字头"],
        name: "Plants and plant products",
        cue: "plants, flowers, herbs, vegetables, or plant-derived materials",
        summary: "艹 at the top is one of the clearest visual clues for plant-related meanings.",
        reliability: "Some meanings have extended from a specific plant or plant product into a broader modern use.",
        examples: [
          { character: "芳", pinyin: "fāng", meaning: "fragrant", semantic: "艹", semanticNote: "plants or flowers", phonetic: "方", phoneticNote: "fāng sound clue", insight: "Fragrance is linked to plants and flowers." },
          { character: "芽", pinyin: "yá", meaning: "sprout; bud", semantic: "艹", semanticNote: "plant", phonetic: "牙", phoneticNote: "yá sound clue", insight: "The component and sound clue are both highly transparent." },
          { character: "菜", pinyin: "cài", meaning: "vegetable; dish", semantic: "艹", semanticNote: "plant food", phonetic: "采", phoneticNote: "approximate sound clue", insight: "The plant clue leads naturally to vegetables and dishes." },
        ],
        questions: [
          { id: "plant-component-1", character: "苗", pinyin: "miáo", prompt: "Which category is the best first guess for 苗?", options: ["A young plant", "A metal tool", "A road", "A feeling"], answer: "A young plant", meaning: "seedling; young plant", decomposition: "艹 (plant) + 田", explanation: "艹 strongly favors a plant-related interpretation; here it is a seedling." },
          { id: "plant-component-2", character: "药", pinyin: "yào", prompt: "What historical category does 艹 suggest in 药?", options: ["Herbs or plant-based medicine", "Speech", "Movement", "Hand action"], answer: "Herbs or plant-based medicine", meaning: "medicine; drug", decomposition: "艹 (plant/herb) + 约 (sound)", explanation: "The component reflects the traditional association between medicine and herbs." },
          { id: "plant-component-3", character: "芽", pinyin: "yá", prompt: "Which component gives 芽 its sound clue?", options: ["牙", "艹", "丿", "一"], answer: "牙", meaning: "sprout; bud", decomposition: "艹 (plant) + 牙 (sound)", explanation: "牙 and 芽 are both pronounced yá; 艹 supplies the plant category." },
        ],
      },
      {
        id: "fire-component",
        component: "火",
        variants: ["灬"],
        name: "Fire, heat, and cooking",
        cue: "fire, heat, burning, light, or cooking",
        summary: "火 can appear on the left or change to 灬 at the bottom.",
        reliability: "Some characters retain a historical fire connection even when the modern meaning is abstract.",
        examples: [
          { character: "炒", pinyin: "chǎo", meaning: "to stir-fry", semantic: "火", semanticNote: "heat or cooking", phonetic: "少", phoneticNote: "approximate sound clue", insight: "The fire clue identifies a cooking method." },
          { character: "烤", pinyin: "kǎo", meaning: "to roast; to bake", semantic: "火", semanticNote: "heat", phonetic: "考", phoneticNote: "kǎo sound clue", insight: "The category and sound clues are both transparent." },
          { character: "煮", pinyin: "zhǔ", meaning: "to boil; to cook", semantic: "灬", semanticNote: "fire or heat at the bottom", phonetic: "者", phoneticNote: "approximate sound clue", insight: "The bottom form points toward cooking with heat." },
        ],
        questions: [
          { id: "fire-component-1", character: "烧", pinyin: "shāo", prompt: "Which meaning category should 火 suggest first?", options: ["Burning or heating", "Speaking", "A person", "Water"], answer: "Burning or heating", meaning: "to burn; to cook; fever", decomposition: "火 (fire) + 尧 (sound)", explanation: "Fire and heat connect the literal and extended meanings of 烧." },
          { id: "fire-component-2", character: "灯", pinyin: "dēng", prompt: "Why is 火 useful in 灯?", options: ["It points toward light or flame", "It marks a road", "It means speech", "It marks a plant"], answer: "It points toward light or flame", meaning: "lamp; light", decomposition: "火 (fire/light) + 丁 (sound)", explanation: "Traditional lamps used flame, so the fire component supplies the semantic category." },
          { id: "fire-component-3", character: "热", pinyin: "rè", prompt: "Which visible part is associated with heat in 热?", options: ["灬", "执", "扌", "丸"], answer: "灬", meaning: "hot; heat", decomposition: "执 + 灬 (fire/heat)", explanation: "The four-dot bottom form is associated with fire and heat." },
        ],
      },
      {
        id: "metal-component",
        component: "钅",
        variants: ["金"],
        name: "Metal, money, and metal objects",
        cue: "metal, tools, coins, minerals, or objects made from metal",
        summary: "钅 is the simplified left-side form of 金 and marks many metals and metal objects.",
        reliability: "The component often identifies material, though modern objects and abstract uses may extend beyond it.",
        examples: [
          { character: "铜", pinyin: "tóng", meaning: "copper", semantic: "钅", semanticNote: "metal", phonetic: "同", phoneticNote: "tóng sound clue", insight: "Both meaning and sound clues are transparent." },
          { character: "银", pinyin: "yín", meaning: "silver", semantic: "钅", semanticNote: "metal", phonetic: "艮", phoneticNote: "historical sound clue", insight: "The metal category remains clear even though the sound relationship is less obvious." },
          { character: "锅", pinyin: "guō", meaning: "cooking pot", semantic: "钅", semanticNote: "metal object", phonetic: "呙", phoneticNote: "guō sound clue", insight: "The component points toward the pot's traditional material." },
        ],
        questions: [
          { id: "metal-component-1", character: "针", pinyin: "zhēn", prompt: "Which category is most likely for 针?", options: ["A small metal object", "A plant", "A feeling", "A spoken phrase"], answer: "A small metal object", meaning: "needle; pin", decomposition: "钅 (metal) + 十 (sound element)", explanation: "钅 makes a metal object the strongest first guess." },
          { id: "metal-component-2", character: "锁", pinyin: "suǒ", prompt: "Which meaning best fits the metal clue?", options: ["Lock", "Lake", "Song", "Root"], answer: "Lock", meaning: "lock; to lock", decomposition: "钅 (metal) + 小/贝-based sound element", explanation: "A lock is traditionally a metal object, so 钅 is a useful category clue." },
          { id: "metal-component-3", character: "铜", pinyin: "tóng", prompt: "Which part supplies the modern sound in 铜?", options: ["同", "钅", "冂", "口"], answer: "同", meaning: "copper", decomposition: "钅 (metal) + 同 (sound)", explanation: "同 and 铜 are both pronounced tóng; 钅 identifies the metal category." },
        ],
      },
    ],
  },
  {
    id: "language-and-life",
    title: "Language and daily life",
    description: "Infer speech, movement, food, and animal meanings from high-frequency components.",
    lessons: [
      {
        id: "speech-component",
        component: "讠",
        variants: ["言"],
        name: "Speech and language",
        cue: "speaking, language, words, requests, or communication",
        summary: "讠 is the simplified side form of 言 and marks many acts of communication.",
        reliability: "The clue can cover spoken language, written language, promises, opinions, and information.",
        examples: [
          { character: "请", pinyin: "qǐng", meaning: "to ask; please", semantic: "讠", semanticNote: "speech", phonetic: "青", phoneticNote: "qīng sound family", insight: "Asking is an action performed with language." },
          { character: "访", pinyin: "fǎng", meaning: "to visit; to inquire", semantic: "讠", semanticNote: "communication", phonetic: "方", phoneticNote: "fāng sound family", insight: "The original semantic field includes asking and inquiring." },
          { character: "记", pinyin: "jì", meaning: "to record; to remember", semantic: "讠", semanticNote: "words or recording", phonetic: "己", phoneticNote: "approximate sound clue", insight: "Words and records support both writing down and remembering." },
        ],
        questions: [
          { id: "speech-component-1", character: "讲", pinyin: "jiǎng", prompt: "What meaning category is most likely from 讠?", options: ["Speaking or explaining", "Cooking", "Swimming", "A metal"], answer: "Speaking or explaining", meaning: "to speak; to explain", decomposition: "讠 (speech) + 冓-derived sound element", explanation: "讠 strongly points toward communication or language." },
          { id: "speech-component-2", character: "词", pinyin: "cí", prompt: "Which meaning best matches the language clue?", options: ["Word or term", "Bridge", "Animal", "Hot"], answer: "Word or term", meaning: "word; term; lyrics", decomposition: "讠 (language) + 司 (sound)", explanation: "A word or term belongs directly to the language category." },
          { id: "speech-component-3", character: "访", pinyin: "fǎng", prompt: "Which part is mainly the sound clue in 访?", options: ["方", "讠", "丶", "万"], answer: "方", meaning: "to visit; to inquire", decomposition: "讠 (communication) + 方 (sound)", explanation: "方 supplies an approximate fāng/fǎng sound relationship while 讠 supplies the communication category." },
        ],
      },
      {
        id: "movement-component",
        component: "辶",
        variants: ["走之"],
        name: "Movement and paths",
        cue: "movement, travel, approach, distance, or routes",
        summary: "辶 commonly marks motion through space or a relationship to a route and distance.",
        reliability: "Some meanings are metaphorical extensions of movement, arrival, passing, or distance.",
        examples: [
          { character: "近", pinyin: "jìn", meaning: "near; to approach", semantic: "辶", semanticNote: "movement or distance", phonetic: "斤", phoneticNote: "jīn sound family", insight: "The route clue supports a spatial meaning." },
          { character: "进", pinyin: "jìn", meaning: "to enter; to advance", semantic: "辶", semanticNote: "movement", phonetic: "井", phoneticNote: "approximate sound clue", insight: "Advancing is direct movement." },
          { character: "远", pinyin: "yuǎn", meaning: "far", semantic: "辶", semanticNote: "distance or route", phonetic: "元", phoneticNote: "yuán sound family", insight: "The component helps frame the character as a spatial relation." },
        ],
        questions: [
          { id: "movement-component-1", character: "追", pinyin: "zhuī", prompt: "What category should 辶 make you consider first?", options: ["Movement or pursuit", "Eating", "Metal", "Emotion"], answer: "Movement or pursuit", meaning: "to chase; to pursue", decomposition: "辶 (movement) + sound element", explanation: "Chasing is movement directed after something." },
          { id: "movement-component-2", character: "逃", pinyin: "táo", prompt: "Which meaning best fits the movement clue?", options: ["To escape", "To taste", "To shine", "To remember"], answer: "To escape", meaning: "to escape; to flee", decomposition: "辶 (movement) + 兆 (sound)", explanation: "Escaping is a movement action, while 兆 supplies the approximate sound." },
          { id: "movement-component-3", character: "近", pinyin: "jìn", prompt: "Which visible part marks distance or movement?", options: ["辶", "斤", "丿", "T"], answer: "辶", meaning: "near; to approach", decomposition: "辶 (movement/distance) + 斤 (sound)", explanation: "辶 supplies the spatial meaning category." },
        ],
      },
      {
        id: "food-component",
        component: "饣",
        variants: ["食"],
        name: "Food and eating",
        cue: "food, meals, hunger, eating, or places connected with food",
        summary: "饣 is the simplified side form of 食 and is a strong clue for food-related meanings.",
        reliability: "The category includes foods, eating states, and businesses or objects connected with meals.",
        examples: [
          { character: "饭", pinyin: "fàn", meaning: "cooked rice; meal", semantic: "饣", semanticNote: "food", phonetic: "反", phoneticNote: "fǎn sound family", insight: "The food category is direct and high frequency." },
          { character: "饱", pinyin: "bǎo", meaning: "full; to have eaten enough", semantic: "饣", semanticNote: "eating state", phonetic: "包", phoneticNote: "bāo sound family", insight: "The component extends from food to the state after eating." },
          { character: "饿", pinyin: "è", meaning: "hungry", semantic: "饣", semanticNote: "food or hunger", phonetic: "我", phoneticNote: "historical sound clue", insight: "Hunger belongs to the food and eating semantic field." },
        ],
        questions: [
          { id: "food-component-1", character: "饼", pinyin: "bǐng", prompt: "Which category is most likely for 饼?", options: ["A kind of food", "A road", "A feeling", "A metal"], answer: "A kind of food", meaning: "cake; pastry; flatbread", decomposition: "饣 (food) + 并 (sound)", explanation: "饣 makes a food item the clear first hypothesis." },
          { id: "food-component-2", character: "饮", pinyin: "yǐn", prompt: "Which meaning best fits 饣?", options: ["To drink", "To push", "To ask", "To burn"], answer: "To drink", meaning: "to drink; beverage", decomposition: "饣 (food/drink) + 欠 (sound element)", explanation: "Drinking belongs to the eating and nourishment category." },
          { id: "food-component-3", character: "饭", pinyin: "fàn", prompt: "Which part supplies the approximate sound in 饭?", options: ["反", "饣", "厂", "又"], answer: "反", meaning: "meal; cooked rice", decomposition: "饣 (food) + 反 (sound)", explanation: "反 provides the fǎn/fàn sound family while 饣 identifies food." },
        ],
      },
      {
        id: "animal-component",
        component: "犭",
        variants: ["犬"],
        name: "Animals",
        cue: "animals, animal behavior, or qualities historically associated with animals",
        summary: "犭 is the side form of 犬 and appears in the names of many animals.",
        reliability: "It is especially strong for animal names, though some characters developed figurative meanings.",
        examples: [
          { character: "猫", pinyin: "māo", meaning: "cat", semantic: "犭", semanticNote: "animal", phonetic: "苗", phoneticNote: "miáo sound family", insight: "The animal category and approximate sound are both visible." },
          { character: "狼", pinyin: "láng", meaning: "wolf", semantic: "犭", semanticNote: "animal", phonetic: "良", phoneticNote: "liáng sound family", insight: "The animal clue identifies the domain immediately." },
          { character: "狗", pinyin: "gǒu", meaning: "dog", semantic: "犭", semanticNote: "animal", phonetic: "句", phoneticNote: "historical sound clue", insight: "Even when the modern sound clue is weak, the animal category remains useful." },
        ],
        questions: [
          { id: "animal-component-1", character: "狐", pinyin: "hú", prompt: "What category is most likely for 狐?", options: ["An animal", "A liquid", "A speech act", "A tool"], answer: "An animal", meaning: "fox", decomposition: "犭 (animal) + 瓜 (sound)", explanation: "犭 is a strong animal-name clue." },
          { id: "animal-component-2", character: "狮", pinyin: "shī", prompt: "Which meaning best fits the component clue?", options: ["Lion", "River", "Lamp", "Question"], answer: "Lion", meaning: "lion", decomposition: "犭 (animal) + 师 (sound)", explanation: "The animal component makes an animal name much more likely than the other choices." },
          { id: "animal-component-3", character: "猫", pinyin: "māo", prompt: "Which part supplies the broad meaning in 猫?", options: ["犭", "苗", "艹", "田"], answer: "犭", meaning: "cat", decomposition: "犭 (animal) + 苗 (sound)", explanation: "犭 identifies the animal category; 苗 contributes the approximate sound." },
        ],
      },
    ],
  },
];

