"use strict";

window.GRAMMAR_LESSONS = [
  {
    id: "hsk1-shi",
    level: 1,
    category: "Sentence pattern",
    title: "Identifying with 是",
    pattern: "A 是 B",
    summary: "Use 是 to identify or classify a person or thing.",
    structure: "Noun or pronoun + 是 + noun or noun phrase",
    note: "Use 是 before a noun identity: 她是老师. With an adjective, normally say 她很忙 rather than 她是忙.",
    examples: [
      { zh: "她是老师。", pinyin: "Tā shì lǎoshī.", en: "She is a teacher." },
      { zh: "这是我的书。", pinyin: "Zhè shì wǒ de shū.", en: "This is my book." },
      { zh: "今天是星期五。", pinyin: "Jīntiān shì xīngqīwǔ.", en: "Today is Friday." },
    ],
    questions: [
      { prompt: "他___我的朋友。", translation: "He is my friend.", options: ["是", "有", "在", "很"], answer: "是", explanation: "是 connects 他 with the noun phrase 我的朋友." },
      { prompt: "明天___星期六。", translation: "Tomorrow is Saturday.", options: ["是", "会", "有", "比"], answer: "是", explanation: "Use 是 to identify a day or date." },
      { prompt: "这___北京大学。", translation: "This is Peking University.", options: ["是", "很", "没", "都"], answer: "是", explanation: "是 identifies what 这 refers to." },
    ],
  },
  {
    id: "hsk1-you",
    level: 1,
    category: "Sentence pattern",
    title: "Having and existing with 有",
    pattern: "A 有 B / Place 有 B",
    summary: "Use 有 for possession and for something existing in a place. Use 没有 to negate it.",
    structure: "Owner or place + 有 / 没有 + noun phrase",
    note: "Do not use 不有. The negative form is always 没有 or its short form 没.",
    examples: [
      { zh: "我有两个姐姐。", pinyin: "Wǒ yǒu liǎng ge jiějie.", en: "I have two older sisters." },
      { zh: "桌子上有一本书。", pinyin: "Zhuōzi shàng yǒu yì běn shū.", en: "There is a book on the table." },
      { zh: "今天没有课。", pinyin: "Jīntiān méiyǒu kè.", en: "There are no classes today." },
    ],
    questions: [
      { prompt: "我___一只猫。", translation: "I have a cat.", options: ["有", "是", "在", "会"], answer: "有", explanation: "有 expresses possession." },
      { prompt: "房间里___三把椅子。", translation: "There are three chairs in the room.", options: ["有", "是", "比", "想"], answer: "有", explanation: "Place + 有 introduces something that exists in that place." },
      { prompt: "他今天___时间。", translation: "He does not have time today.", options: ["没有", "不会", "不是", "不在"], answer: "没有", explanation: "The negative of 有 is 没有, never 不有." },
    ],
  },
  {
    id: "hsk1-de",
    level: 1,
    category: "Noun phrase",
    title: "Connecting descriptions with 的",
    pattern: "Description + 的 + noun",
    summary: "Use 的 to connect an owner or description to a noun.",
    structure: "Possessor, pronoun, or description + 的 + noun",
    note: "With close family relationships, 的 is often omitted: 我妈妈. Keep it when ownership or contrast needs emphasis.",
    examples: [
      { zh: "这是我的手机。", pinyin: "Zhè shì wǒ de shǒujī.", en: "This is my phone." },
      { zh: "穿红衣服的人是王老师。", pinyin: "Chuān hóng yīfu de rén shì Wáng lǎoshī.", en: "The person wearing red is Teacher Wang." },
      { zh: "我喜欢你买的茶。", pinyin: "Wǒ xǐhuan nǐ mǎi de chá.", en: "I like the tea you bought." },
    ],
    questions: [
      { prompt: "这是我___书。", translation: "This is my book.", options: ["的", "得", "地", "了"], answer: "的", explanation: "的 connects 我, the owner, to 书." },
      { prompt: "那个说汉语___人是谁？", translation: "Who is that person speaking Chinese?", options: ["的", "得", "在", "过"], answer: "的", explanation: "The phrase 说汉语 describes 人, so it is followed by 的." },
      { prompt: "我想买便宜___电脑。", translation: "I want to buy an inexpensive computer.", options: ["的", "得", "了", "吗"], answer: "的", explanation: "的 links the description 便宜 to the noun 电脑." },
    ],
  },
  {
    id: "hsk1-ma",
    level: 1,
    category: "Questions",
    title: "Yes-no questions with 吗",
    pattern: "Statement + 吗？",
    summary: "Turn a statement into a neutral yes-no question by adding 吗 at the end.",
    structure: "Subject + predicate + 吗？",
    note: "Do not add 吗 to a question that already uses a question word such as 谁, 什么, or 哪儿.",
    examples: [
      { zh: "你是学生吗？", pinyin: "Nǐ shì xuésheng ma?", en: "Are you a student?" },
      { zh: "你喜欢喝茶吗？", pinyin: "Nǐ xǐhuan hē chá ma?", en: "Do you like drinking tea?" },
      { zh: "他今天来吗？", pinyin: "Tā jīntiān lái ma?", en: "Is he coming today?" },
    ],
    questions: [
      { prompt: "你会说中文___？", translation: "Can you speak Chinese?", options: ["吗", "呢", "的", "了"], answer: "吗", explanation: "The sentence is a yes-no question, so 吗 goes at the end." },
      { prompt: "她是你的老师___？", translation: "Is she your teacher?", options: ["吗", "谁", "什么", "哪儿"], answer: "吗", explanation: "吗 turns the statement into a neutral yes-no question." },
      { prompt: "你明天有时间___？", translation: "Do you have time tomorrow?", options: ["吗", "怎么", "哪", "几"], answer: "吗", explanation: "There is no question word, so 吗 marks the yes-no question." },
    ],
  },
  {
    id: "hsk1-a-not-a",
    level: 1,
    category: "Questions",
    title: "Positive-negative questions",
    pattern: "A 不 A / 有没有",
    summary: "Repeat the predicate in positive and negative form to ask for a yes-no answer.",
    structure: "Subject + verb or adjective + 不 + verb or adjective？",
    note: "With 有, use 有没有. A positive-negative question normally does not also take 吗.",
    examples: [
      { zh: "你是不是老师？", pinyin: "Nǐ shì bu shì lǎoshī?", en: "Are you a teacher?" },
      { zh: "这个菜好不好吃？", pinyin: "Zhège cài hǎo bu hǎochī?", en: "Does this dish taste good?" },
      { zh: "你有没有哥哥？", pinyin: "Nǐ yǒu méiyǒu gēge?", en: "Do you have an older brother?" },
    ],
    questions: [
      { prompt: "你___想喝咖啡？", translation: "Do you want to drink coffee?", options: ["想不想", "是不是", "有没有", "会不会"], answer: "想不想", explanation: "The positive-negative form of 想 is 想不想." },
      { prompt: "他___学生？", translation: "Is he a student?", options: ["是不是", "有没有", "会不会", "好不好"], answer: "是不是", explanation: "The positive-negative form of 是 is 是不是." },
      { prompt: "你___时间？", translation: "Do you have time?", options: ["有没有", "是不是", "会不会", "想不想"], answer: "有没有", explanation: "有 uses the special positive-negative form 有没有." },
    ],
  },
  {
    id: "hsk1-progressive",
    level: 1,
    category: "Aspect",
    title: "Actions in progress",
    pattern: "在 / 正在 + verb (+ 呢)",
    summary: "Place 在, 正, or 正在 before a verb to show that an action is happening now.",
    structure: "Subject + 在 / 正在 + verb phrase + 呢",
    note: "呢 is optional when 在 or 正在 already marks the action as ongoing.",
    examples: [
      { zh: "我正在看书。", pinyin: "Wǒ zhèngzài kàn shū.", en: "I am reading." },
      { zh: "妈妈在做饭呢。", pinyin: "Māma zài zuò fàn ne.", en: "Mom is cooking." },
      { zh: "他们正上课呢。", pinyin: "Tāmen zhèng shàng kè ne.", en: "They are in class right now." },
    ],
    questions: [
      { prompt: "我___听音乐。", translation: "I am listening to music.", options: ["正在", "已经", "过", "比"], answer: "正在", explanation: "正在 before the verb marks an action happening now." },
      { prompt: "他在打电话___。", translation: "He is making a phone call.", options: ["呢", "吗", "的", "过"], answer: "呢", explanation: "呢 can reinforce that the action is currently in progress." },
      { prompt: "孩子们___睡觉。", translation: "The children are sleeping right now.", options: ["正", "已经", "常常", "一起"], answer: "正", explanation: "正 directly before the verb emphasizes 'right now.'" },
    ],
  },
  {
    id: "hsk1-bi",
    level: 1,
    category: "Comparison",
    title: "Comparing with 比",
    pattern: "A 比 B + adjective",
    summary: "Use 比 to say that A has more of a quality than B.",
    structure: "A + 比 + B + adjective",
    note: "Do not normally add 很 after 比. To say A is not as adjective as B, use A 没有 B + adjective.",
    examples: [
      { zh: "今天比昨天冷。", pinyin: "Jīntiān bǐ zuótiān lěng.", en: "Today is colder than yesterday." },
      { zh: "哥哥比我高。", pinyin: "Gēge bǐ wǒ gāo.", en: "My older brother is taller than me." },
      { zh: "这本书没有那本书贵。", pinyin: "Zhè běn shū méiyǒu nà běn shū guì.", en: "This book is not as expensive as that one." },
    ],
    questions: [
      { prompt: "上海___北京暖和。", translation: "Shanghai is warmer than Beijing.", options: ["比", "跟", "有", "在"], answer: "比", explanation: "比 introduces the standard being compared: 北京." },
      { prompt: "妹妹比我___。", translation: "My younger sister is younger than me.", options: ["小", "很小", "一样小", "没有小"], answer: "小", explanation: "The adjective follows the 比 phrase directly; 很 is not needed." },
      { prompt: "今天___昨天热。", translation: "Today is not as hot as yesterday.", options: ["没有", "不是", "不在", "还没"], answer: "没有", explanation: "A 没有 B + adjective means A is not as adjective as B." },
    ],
  },
  {
    id: "hsk1-le",
    level: 1,
    category: "Aspect",
    title: "Completed actions and new situations",
    pattern: "Verb + 了 / Sentence + 了",
    summary: "Use 了 after a verb for a completed action or at the end of a sentence for a new situation.",
    structure: "Subject + verb + 了 + object; or statement + 了",
    note: "Verb 了 focuses on completion. Sentence-final 了 signals that the situation has changed, as in 下雨了.",
    examples: [
      { zh: "我买了一本书。", pinyin: "Wǒ mǎi le yì běn shū.", en: "I bought a book." },
      { zh: "他回家了。", pinyin: "Tā huí jiā le.", en: "He went home." },
      { zh: "天气冷了。", pinyin: "Tiānqì lěng le.", en: "The weather has become cold." },
    ],
    questions: [
      { prompt: "昨天我看___一部电影。", translation: "Yesterday I watched a movie.", options: ["了", "着", "得", "的"], answer: "了", explanation: "了 after 看 marks the action as completed." },
      { prompt: "快十二点___。", translation: "It is almost twelve now.", options: ["了", "过", "着", "得"], answer: "了", explanation: "Sentence-final 了 marks a new situation: it is now nearly twelve." },
      { prompt: "雨停___，我们走吧。", translation: "The rain has stopped; let's go.", options: ["了", "得", "的", "在"], answer: "了", explanation: "了 shows that the situation has changed: the rain has stopped." },
    ],
  },
  {
    id: "hsk2-guo",
    level: 2,
    category: "Aspect",
    title: "Past experience with 过",
    pattern: "Verb + 过",
    summary: "Use 过 to say that an event has occurred at least once as part of someone's experience.",
    structure: "Subject + verb + 过 + object",
    note: "The negative is 没(有) + verb + 过. 过 presents experience, not simply one completed event.",
    examples: [
      { zh: "我去过上海。", pinyin: "Wǒ qù guo Shànghǎi.", en: "I have been to Shanghai." },
      { zh: "你吃过北京烤鸭吗？", pinyin: "Nǐ chī guo Běijīng kǎoyā ma?", en: "Have you eaten Peking duck?" },
      { zh: "她没看过这部电影。", pinyin: "Tā méi kàn guo zhè bù diànyǐng.", en: "She has not seen this movie." },
    ],
    questions: [
      { prompt: "我学___一点儿日语。", translation: "I have studied a little Japanese before.", options: ["过", "着", "得", "在"], answer: "过", explanation: "过 after 学 marks prior experience." },
      { prompt: "你去___长城吗？", translation: "Have you been to the Great Wall?", options: ["过", "着", "得", "的"], answer: "过", explanation: "去过 asks whether the visit is part of the listener's experience." },
      { prompt: "他___喝过咖啡。", translation: "He has never drunk coffee.", options: ["没", "不", "别", "不要"], answer: "没", explanation: "The negative pattern for experience is 没 + verb + 过." },
    ],
  },
  {
    id: "hsk2-zhe",
    level: 2,
    category: "Aspect",
    title: "Continuing states with 着",
    pattern: "Verb + 着",
    summary: "Use 着 after a verb to show that a state or action continues.",
    structure: "Subject + verb + 着 + object",
    note: "着 often describes a continuing posture or resulting state: 门开着. It differs from 正在, which foregrounds an action in progress.",
    examples: [
      { zh: "门开着。", pinyin: "Mén kāi zhe.", en: "The door is open." },
      { zh: "墙上挂着一张照片。", pinyin: "Qiáng shàng guà zhe yì zhāng zhàopiàn.", en: "A photograph is hanging on the wall." },
      { zh: "他笑着说话。", pinyin: "Tā xiào zhe shuōhuà.", en: "He speaks while smiling." },
    ],
    questions: [
      { prompt: "她手里拿___一本书。", translation: "She is holding a book in her hand.", options: ["着", "过", "得", "了"], answer: "着", explanation: "拿着 describes the continuing state of holding something." },
      { prompt: "窗户开___，有点儿冷。", translation: "The window is open, so it is a little cold.", options: ["着", "过", "在", "得"], answer: "着", explanation: "开着 describes the window's continuing open state." },
      { prompt: "他一直穿___一件蓝衣服。", translation: "He keeps wearing a blue item of clothing.", options: ["着", "过", "得", "在"], answer: "着", explanation: "穿着 describes a continuing state of wearing." },
    ],
  },
  {
    id: "hsk2-de-complement",
    level: 2,
    category: "Complement",
    title: "Describing performance with 得",
    pattern: "Verb + 得 + description",
    summary: "Use 得 after a verb to describe how well, quickly, or in what manner an action is performed.",
    structure: "Subject + verb + 得 + adjective or descriptive phrase",
    note: "When the verb has an object, the verb is commonly repeated: 她汉语说得很好 or 她说汉语说得很好.",
    examples: [
      { zh: "他说得很快。", pinyin: "Tā shuō de hěn kuài.", en: "He speaks very quickly." },
      { zh: "你写得真漂亮。", pinyin: "Nǐ xiě de zhēn piàoliang.", en: "You write beautifully." },
      { zh: "她汉语说得很好。", pinyin: "Tā Hànyǔ shuō de hěn hǎo.", en: "She speaks Chinese very well." },
    ],
    questions: [
      { prompt: "弟弟跑___很快。", translation: "My younger brother runs very fast.", options: ["得", "的", "地", "了"], answer: "得", explanation: "得 introduces the description 很快 after the verb 跑." },
      { prompt: "你唱___真好听。", translation: "You sing beautifully.", options: ["得", "的", "着", "过"], answer: "得", explanation: "得 connects the action 唱 with how it sounds." },
      { prompt: "他中文说___怎么样？", translation: "How well does he speak Chinese?", options: ["得", "的", "了", "在"], answer: "得", explanation: "Verb + 得 + 怎么样 asks about the manner or quality of an action." },
    ],
  },
  {
    id: "hsk2-shi-de",
    level: 2,
    category: "Emphasis",
    title: "Emphasizing details with 是……的",
    pattern: "是 + detail + verb + 的",
    summary: "Use 是……的 to emphasize when, where, how, or by whom a completed event happened.",
    structure: "Subject + 是 + emphasized detail + verb + 的",
    note: "This pattern discusses a known event and spotlights one detail; it is not the ordinary 是 sentence used for identity.",
    examples: [
      { zh: "我是昨天来的。", pinyin: "Wǒ shì zuótiān lái de.", en: "I came yesterday." },
      { zh: "这张照片是在北京拍的。", pinyin: "Zhè zhāng zhàopiàn shì zài Běijīng pāi de.", en: "This photograph was taken in Beijing." },
      { zh: "你是怎么知道的？", pinyin: "Nǐ shì zěnme zhīdào de?", en: "How did you find out?" },
    ],
    questions: [
      { prompt: "我___坐地铁来___。", translation: "I came by subway.", options: ["是…的", "正在…呢", "已经…了", "要…吗"], answer: "是…的", explanation: "是……的 emphasizes the means of travel, 坐地铁." },
      { prompt: "他___去年开始学中文___。", translation: "He started learning Chinese last year.", options: ["是…的", "正在…呢", "已经…了", "会…吗"], answer: "是…的", explanation: "是……的 emphasizes the time 去年." },
      { prompt: "这个蛋糕___妈妈做___。", translation: "Mom made this cake.", options: ["是…的", "在…呢", "有…吗", "比…了"], answer: "是…的", explanation: "是……的 emphasizes the person who performed the completed action." },
    ],
  },
  {
    id: "hsk2-yuelaiyue",
    level: 2,
    category: "Change",
    title: "Gradual change with 越来越",
    pattern: "越来越 + adjective / mental verb",
    summary: "Use 越来越 to show that a quality or state keeps increasing over time.",
    structure: "Subject + 越来越 + adjective or selected mental verb",
    note: "越来越 expresses change along one timeline. It differs from 越……越……, which links two changing conditions.",
    examples: [
      { zh: "天气越来越热了。", pinyin: "Tiānqì yuèláiyuè rè le.", en: "The weather is getting hotter and hotter." },
      { zh: "她的中文越来越好了。", pinyin: "Tā de Zhōngwén yuèláiyuè hǎo le.", en: "Her Chinese is getting better and better." },
      { zh: "我越来越喜欢这个城市。", pinyin: "Wǒ yuèláiyuè xǐhuan zhège chéngshì.", en: "I like this city more and more." },
    ],
    questions: [
      { prompt: "孩子___高了。", translation: "The child is getting taller and taller.", options: ["越来越", "已经很", "有一点", "还是很"], answer: "越来越", explanation: "越来越 marks a gradual increase in height over time." },
      { prompt: "这里的人___多。", translation: "There are more and more people here.", options: ["越来越", "非常", "特别", "不太"], answer: "越来越", explanation: "越来越多 means the number keeps increasing." },
      { prompt: "我___想家。", translation: "I miss home more and more.", options: ["越来越", "有一点", "常常", "不太"], answer: "越来越", explanation: "越来越 can modify a mental-state verb such as 想." },
    ],
  },
  {
    id: "hsk2-because",
    level: 2,
    category: "Complex sentence",
    title: "Cause and result",
    pattern: "因为……所以……",
    summary: "Use 因为 to introduce a reason and 所以 to introduce its result.",
    structure: "因为 + reason, 所以 + result",
    note: "In conversation, either 因为 or 所以 may be omitted when the relationship is already clear, but the full pair is useful for learning the logic.",
    examples: [
      { zh: "因为下雨，所以我们没出去。", pinyin: "Yīnwèi xiàyǔ, suǒyǐ wǒmen méi chūqu.", en: "Because it rained, we did not go out." },
      { zh: "因为他生病了，所以没来上课。", pinyin: "Yīnwèi tā shēngbìng le, suǒyǐ méi lái shàng kè.", en: "Because he was ill, he did not come to class." },
      { zh: "我很喜欢中文，所以每天都学习。", pinyin: "Wǒ hěn xǐhuan Zhōngwén, suǒyǐ měitiān dōu xuéxí.", en: "I like Chinese, so I study every day." },
    ],
    questions: [
      { prompt: "___今天很冷，___我穿了大衣。", translation: "Because it is cold today, I put on a coat.", options: ["因为…所以…", "虽然…但是…", "如果…就…", "一边…一边…"], answer: "因为…所以…", explanation: "The first clause gives the cause and the second gives its result." },
      { prompt: "___明天要考试，___他今晚不出去。", translation: "Because there is an exam tomorrow, he is not going out tonight.", options: ["因为…所以…", "虽然…但是…", "如果…就…", "只要…就…"], answer: "因为…所以…", explanation: "因为 introduces the reason; 所以 introduces the decision that follows." },
      { prompt: "___我没带钱，___不能买咖啡。", translation: "Because I did not bring money, I cannot buy coffee.", options: ["因为…所以…", "虽然…但是…", "如果…就…", "只要…就…"], answer: "因为…所以…", explanation: "The inability to buy coffee is the result of not bringing money." },
    ],
  },
  {
    id: "hsk2-although",
    level: 2,
    category: "Complex sentence",
    title: "Contrast with 虽然……但是……",
    pattern: "虽然……但是……",
    summary: "Use 虽然 to acknowledge one fact and 但是 to introduce a contrasting result.",
    structure: "虽然 + fact, 但是 + unexpected or contrasting fact",
    note: "可是 or 不过 can often replace 但是 in conversation.",
    examples: [
      { zh: "虽然下雨，但是我们还是去了。", pinyin: "Suīrán xiàyǔ, dànshì wǒmen háishi qù le.", en: "Although it rained, we still went." },
      { zh: "这件衣服虽然贵，但是很好看。", pinyin: "Zhè jiàn yīfu suīrán guì, dànshì hěn hǎokàn.", en: "Although this clothing is expensive, it looks very good." },
      { zh: "他虽然很累，但是还在工作。", pinyin: "Tā suīrán hěn lèi, dànshì hái zài gōngzuò.", en: "Although he is tired, he is still working." },
    ],
    questions: [
      { prompt: "___这本书很长，___很有意思。", translation: "Although this book is long, it is very interesting.", options: ["虽然…但是…", "因为…所以…", "如果…就…", "先…然后…"], answer: "虽然…但是…", explanation: "The second fact contrasts with what the first might lead us to expect." },
      { prompt: "___她感冒了，___她还是来上课了。", translation: "Although she has a cold, she still came to class.", options: ["虽然…但是…", "只要…就…", "一…就…", "又…又…"], answer: "虽然…但是…", explanation: "Coming to class contrasts with the fact that she has a cold." },
      { prompt: "___我不会做饭，___我想学。", translation: "Although I cannot cook, I want to learn.", options: ["虽然…但是…", "因为…所以…", "是…的", "越来越"], answer: "虽然…但是…", explanation: "虽然……但是…… presents two facts in contrast." },
    ],
  },
  {
    id: "hsk2-if",
    level: 2,
    category: "Complex sentence",
    title: "Conditions with 如果……就……",
    pattern: "如果……就……",
    summary: "Use 如果 to present a possible condition and 就 to introduce what follows from it.",
    structure: "如果 + condition, subject + 就 + result",
    note: "The subject of the result usually comes before 就: 如果你有时间，你就来吧.",
    examples: [
      { zh: "如果明天下雨，我们就不去。", pinyin: "Rúguǒ míngtiān xiàyǔ, wǒmen jiù bú qù.", en: "If it rains tomorrow, we will not go." },
      { zh: "如果你累了，就休息一下。", pinyin: "Rúguǒ nǐ lèi le, jiù xiūxi yíxià.", en: "If you are tired, take a short rest." },
      { zh: "如果有问题，就问老师。", pinyin: "Rúguǒ yǒu wèntí, jiù wèn lǎoshī.", en: "If you have a question, ask the teacher." },
    ],
    questions: [
      { prompt: "___你喜欢，___买吧。", translation: "If you like it, buy it.", options: ["如果…就…", "虽然…但是…", "因为…所以…", "一边…一边…"], answer: "如果…就…", explanation: "Liking it is the condition; buying it is the suggested result." },
      { prompt: "___他今天没空，我们___明天见。", translation: "If he is not free today, we will meet tomorrow.", options: ["如果…就…", "因为…所以…", "虽然…但是…", "只要…就…"], answer: "如果…就…", explanation: "如果 introduces a possible condition and 就 introduces the plan." },
      { prompt: "___你不懂，___告诉我。", translation: "If you do not understand, tell me.", options: ["如果…就…", "因为…所以…", "虽然…但是…", "只要…就…"], answer: "如果…就…", explanation: "The second clause tells what to do if the first condition is true." },
    ],
  },
  {
    id: "hsk3-ba",
    level: 3,
    category: "Special sentence",
    title: "Handling an object with 把",
    pattern: "Subject + 把 + object + verb + result",
    summary: "Use 把 to foreground a specific object and say what happens to it.",
    structure: "Subject + 把 + specific object + verb + result, destination, or recipient",
    note: "A 把 sentence normally needs more than a bare verb. Add a result, location, direction, quantity, or recipient that shows how the object is affected.",
    examples: [
      { zh: "请把门关上。", pinyin: "Qǐng bǎ mén guān shàng.", en: "Please close the door." },
      { zh: "我把书放在桌子上了。", pinyin: "Wǒ bǎ shū fàng zài zhuōzi shàng le.", en: "I put the book on the table." },
      { zh: "她把照片发给我了。", pinyin: "Tā bǎ zhàopiàn fā gěi wǒ le.", en: "She sent the photograph to me." },
    ],
    questions: [
      { prompt: "请___名字写在这里。", translation: "Please write your name here.", options: ["把", "被", "从", "对"], answer: "把", explanation: "把 places the specific object 名字 before the action that affects it." },
      { prompt: "我把作业___老师了。", translation: "I handed the homework to the teacher.", options: ["交给", "交在", "给被", "把给"], answer: "交给", explanation: "交给 names the result and recipient of the action in the 把 sentence." },
      { prompt: "他___房间打扫干净了。", translation: "He cleaned the room thoroughly.", options: ["把", "被", "向", "从"], answer: "把", explanation: "房间 is a specific object affected by 打扫干净, so it follows 把." },
    ],
  },
  {
    id: "hsk3-bei",
    level: 3,
    category: "Special sentence",
    title: "Describing passive events with 被",
    pattern: "Subject + 被 + agent + verb + result",
    summary: "Use 被 when the subject undergoes an action, optionally naming who or what caused it.",
    structure: "Affected subject + 被 + agent (optional) + verb + other elements",
    note: "The agent can be omitted when it is unknown or unimportant. As with 把, the verb usually includes a result or another element that completes the event.",
    examples: [
      { zh: "我的自行车被别人骑走了。", pinyin: "Wǒ de zìxíngchē bèi biérén qí zǒu le.", en: "My bicycle was ridden away by someone else." },
      { zh: "门被弟弟打开了。", pinyin: "Mén bèi dìdi dǎkāi le.", en: "The door was opened by my younger brother." },
      { zh: "杯子被弟弟打坏了。", pinyin: "Bēizi bèi dìdi dǎ huài le.", en: "The cup was broken by my younger brother." },
    ],
    questions: [
      { prompt: "她的手机___人拿走了。", translation: "Her phone was taken away by someone.", options: ["被", "把", "对", "从"], answer: "被", explanation: "The phone undergoes the action, so 被 introduces the agent 人." },
      { prompt: "门___弟弟打开了。", translation: "The door was opened by my younger brother.", options: ["被", "把", "向", "给"], answer: "被", explanation: "门 undergoes the action, which makes this a passive 被 sentence." },
      { prompt: "杯子被弟弟___了。", translation: "The cup was broken by my younger brother.", options: ["打坏", "打在", "坏把", "开着"], answer: "打坏", explanation: "打坏 gives the completed result of the passive action." },
    ],
  },
  {
    id: "hsk3-potential-complement",
    level: 3,
    category: "Complement",
    title: "Ability with potential complements",
    pattern: "Verb + 得 / 不 + result",
    summary: "Place 得 or 不 between a verb and its complement to say whether a result can be achieved.",
    structure: "Verb + 得 + complement; or verb + 不 + complement",
    note: "Potential complements describe whether the action can reach its result in the situation. They are different from 会, which often describes learned ability.",
    examples: [
      { zh: "我看得懂这篇课文。", pinyin: "Wǒ kàn de dǒng zhè piān kèwén.", en: "I can understand this text when I read it." },
      { zh: "声音太小，我听不清楚。", pinyin: "Shēngyīn tài xiǎo, wǒ tīng bu qīngchu.", en: "The sound is too quiet; I cannot hear it clearly." },
      { zh: "这张桌子搬不进去。", pinyin: "Zhè zhāng zhuōzi bān bu jìnqu.", en: "This table cannot be moved inside." },
    ],
    questions: [
      { prompt: "这篇课文不难，我看___。", translation: "This text is not difficult; I can understand it.", options: ["得懂", "不懂", "得见", "不见"], answer: "得懂", explanation: "看得懂 means the result of understanding can be achieved by reading." },
      { prompt: "声音太小，我听___。", translation: "The sound is too quiet; I cannot hear it clearly.", options: ["不清楚", "得清楚", "着清楚", "了清楚"], answer: "不清楚", explanation: "听不清楚 says that hearing cannot reach the result 清楚." },
      { prompt: "箱子太大，电梯里放___。", translation: "The box is too large; it will not fit in the elevator.", options: ["不下", "得下", "着下", "了下"], answer: "不下", explanation: "放不下 means there is not enough room for the object to fit." },
    ],
  },
  {
    id: "hsk3-result-complement",
    level: 3,
    category: "Complement",
    title: "Completing an action with a result",
    pattern: "Verb + 到 / 住 / 走 / 上",
    summary: "Add a result complement to show what an action achieves or how it changes its object.",
    structure: "Action verb + result complement",
    note: "The complement carries the result: 找到 means succeed in finding, 记住 means retain in memory, and 拿走 means take something away.",
    examples: [
      { zh: "我终于找到了手机。", pinyin: "Wǒ zhōngyú zhǎodào le shǒujī.", en: "I finally found the phone." },
      { zh: "请记住这个号码。", pinyin: "Qǐng jìzhù zhège hàomǎ.", en: "Please remember this number." },
      { zh: "他拿走了桌上的杯子。", pinyin: "Tā názǒu le zhuō shàng de bēizi.", en: "He took away the cup on the table." },
    ],
    questions: [
      { prompt: "我终于找___手机了。", translation: "I finally found the phone.", options: ["到", "住", "走", "上"], answer: "到", explanation: "找到 says that the search reached the result of finding the object." },
      { prompt: "请记___这个号码。", translation: "Please remember this number.", options: ["住", "到", "走", "上"], answer: "住", explanation: "记住 means to retain something firmly in memory." },
      { prompt: "是谁把我的伞拿___了？", translation: "Who took my umbrella away?", options: ["走", "住", "到", "上"], answer: "走", explanation: "拿走 shows that the object is removed from its original place." },
    ],
  },
  {
    id: "hsk3-yue-yue",
    level: 3,
    category: "Change",
    title: "Linked change with 越……越……",
    pattern: "越 A，越 B",
    summary: "Use 越……越…… when one changing condition develops together with another.",
    structure: "Subject + 越 + predicate 1, subject + 越 + predicate 2",
    note: "This differs from 越来越, which describes one quality changing over time. 越……越…… explicitly links two changing predicates.",
    examples: [
      { zh: "你越练习，说得越好。", pinyin: "Nǐ yuè liànxí, shuō de yuè hǎo.", en: "The more you practice, the better you speak." },
      { zh: "天气越冷，我越想喝热茶。", pinyin: "Tiānqì yuè lěng, wǒ yuè xiǎng hē rè chá.", en: "The colder the weather, the more I want to drink hot tea." },
      { zh: "这篇课文我越读越喜欢。", pinyin: "Zhè piān kèwén wǒ yuè dú yuè xǐhuan.", en: "The more I read this text, the more I like it." },
    ],
    questions: [
      { prompt: "你___练习，中文___好。", translation: "The more you practice, the better your Chinese becomes.", options: ["越…越…", "又…又…", "先…再…", "因为…所以…"], answer: "越…越…", explanation: "Two linked changes are expressed with 越 before each predicate." },
      { prompt: "天气___冷，我___想喝热茶。", translation: "The colder the weather, the more I want hot tea.", options: ["越…越…", "一边…一边…", "虽然…但是…", "除了…还…"], answer: "越…越…", explanation: "The desire changes together with the temperature." },
      { prompt: "这篇课文我___读___喜欢。", translation: "The more I read this text, the more I like it.", options: ["越…越…", "又…又…", "一…就…", "先…然后…"], answer: "越…越…", explanation: "越读越喜欢 links continued reading with growing enjoyment." },
    ],
  },
  {
    id: "hsk3-chule",
    level: 3,
    category: "Fixed pattern",
    title: "Adding or excluding with 除了",
    pattern: "除了……（以外），还 / 也 / 都……",
    summary: "Use 除了 to set one item apart, then add another fact or describe what is true of everyone else.",
    structure: "除了 + item + (以外), subject + 还 / 也 / 都 + predicate",
    note: "还 and 也 usually add information: 'besides.' 都 often describes an exception: 'except for.' Context tells which relationship is intended.",
    examples: [
      { zh: "除了汉语以外，她还在学一种外语。", pinyin: "Chúle Hànyǔ yǐwài, tā hái zài xué yì zhǒng wàiyǔ.", en: "Besides Chinese, she is also studying a foreign language." },
      { zh: "除了星期天，我每天都上班。", pinyin: "Chúle xīngqītiān, wǒ měitiān dōu shàngbān.", en: "Except for Sunday, I work every day." },
      { zh: "班上除了我以外，大家都去过北京。", pinyin: "Bān shàng chúle wǒ yǐwài, dàjiā dōu qù guo Běijīng.", en: "Everyone in the class except me has been to Beijing." },
    ],
    questions: [
      { prompt: "___咖啡___，我还喜欢喝茶。", translation: "Besides coffee, I also like drinking tea.", options: ["除了…以外…", "因为…所以…", "虽然…但是…", "只有…才…"], answer: "除了…以外…", explanation: "除了……以外 sets coffee apart before 还 adds another preference." },
      { prompt: "___小李，大家___到了。", translation: "Everyone except Xiao Li has arrived.", options: ["除了…都…", "不但…而且…", "只要…就…", "越…越…"], answer: "除了…都…", explanation: "除了 names the exception and 都 describes everyone else." },
      { prompt: "这里___安静___很方便。", translation: "Besides being quiet, this place is also convenient.", options: ["除了…以外…还…", "只有…才…", "如果…就…", "虽然…但是…"], answer: "除了…以外…还…", explanation: "还 adds convenience as a second quality beyond quietness." },
    ],
  },
  {
    id: "hsk3-budan",
    level: 3,
    category: "Complex sentence",
    title: "Building emphasis with 不但……而且……",
    pattern: "不但……而且……",
    summary: "Use 不但……而且…… to add a second fact that strengthens or extends the first.",
    structure: "Subject + 不但 + predicate 1, 而且 + predicate 2",
    note: "When both clauses share a subject, put it before 不但. 而且 can introduce a stronger, more surprising, or simply additional fact.",
    examples: [
      { zh: "她不但会唱歌，而且会跳舞。", pinyin: "Tā bùdàn huì chànggē, érqiě huì tiàowǔ.", en: "She can not only sing but also dance." },
      { zh: "这个办法不但简单，而且很有用。", pinyin: "Zhège bànfǎ bùdàn jiǎndān, érqiě hěn yǒuyòng.", en: "This method is not only simple but also useful." },
      { zh: "他不但没迟到，而且来得最早。", pinyin: "Tā bùdàn méi chídào, érqiě lái de zuì zǎo.", en: "Not only was he not late, he arrived earliest." },
    ],
    questions: [
      { prompt: "她___会跳舞，___会唱歌。", translation: "She can not only dance but also sing.", options: ["不但…而且…", "虽然…但是…", "因为…所以…", "只有…才…"], answer: "不但…而且…", explanation: "The second ability adds to the first, so use 不但……而且……." },
      { prompt: "这家饭店___便宜，___很好吃。", translation: "This restaurant is not only inexpensive but also very good.", options: ["不但…而且…", "如果…就…", "越…越…", "除了…都…"], answer: "不但…而且…", explanation: "而且 adds a second positive quality to the first." },
      { prompt: "他___完成了工作，___帮助了同事。", translation: "He not only finished his work but also helped a colleague.", options: ["不但…而且…", "一边…一边…", "只有…才…", "虽然…可是…"], answer: "不但…而且…", explanation: "The second completed action extends the first achievement." },
    ],
  },
  {
    id: "hsk3-zhiyou",
    level: 3,
    category: "Complex sentence",
    title: "Necessary conditions with 只有……才……",
    pattern: "只有……才……",
    summary: "Use 只有……才…… when a result can happen only if a necessary condition is met.",
    structure: "只有 + necessary condition, subject + 才 + result",
    note: "This pattern is restrictive: without the 只有 condition, the 才 result does not follow. It is stronger than a general 如果……就…… condition.",
    examples: [
      { zh: "只有多练习，中文才会更好。", pinyin: "Zhǐyǒu duō liànxí, Zhōngwén cái huì gèng hǎo.", en: "Only with more practice will your Chinese improve." },
      { zh: "只有你知道号码，才能给他打电话。", pinyin: "Zhǐyǒu nǐ zhīdào hàomǎ, cái néng gěi tā dǎ diànhuà.", en: "Only if you know the number can you call him." },
      { zh: "只有坐地铁，才来得及。", pinyin: "Zhǐyǒu zuò dìtiě, cái lái de jí.", en: "Only by taking the subway can we make it in time." },
    ],
    questions: [
      { prompt: "___认真复习，___能通过考试。", translation: "Only by reviewing carefully can you pass the exam.", options: ["只有…才…", "只要…就…", "如果…就…", "因为…所以…"], answer: "只有…才…", explanation: "The sentence presents careful review as a necessary condition." },
      { prompt: "___学生___可以进入这个教室。", translation: "Only students may enter this classroom.", options: ["只有…才…", "不但…而且…", "虽然…但是…", "越…越…"], answer: "只有…才…", explanation: "Being a student is required for the result 可以进入这个教室." },
      { prompt: "___早点儿出发，我们___不会迟到。", translation: "Only if we leave earlier will we avoid being late.", options: ["只有…才…", "只要…就…", "除了…还…", "一边…一边…"], answer: "只有…才…", explanation: "早点儿出发 is framed as the necessary condition for not being late." },
    ],
  },
  {
    id: "hsk3-zhiyao",
    level: 3,
    category: "Complex sentence",
    title: "Sufficient conditions with 只要……就……",
    pattern: "只要……就……",
    summary: "Use 只要……就…… when meeting one condition is enough for a result to follow.",
    structure: "只要 + sufficient condition, subject + 就 + result",
    note: "只要 presents a sufficient condition: once it is met, the result follows. Compare 只有……才……, which presents a necessary condition.",
    examples: [
      { zh: "只要不下雨，我们就去爬山。", pinyin: "Zhǐyào bú xiàyǔ, wǒmen jiù qù páshān.", en: "As long as it does not rain, we will go hiking." },
      { zh: "只要你愿意，我就帮你。", pinyin: "Zhǐyào nǐ yuànyì, wǒ jiù bāng nǐ.", en: "As long as you are willing, I will help you." },
      { zh: "只要每天复习，就能记住这些词。", pinyin: "Zhǐyào měitiān fùxí, jiù néng jìzhù zhèxiē cí.", en: "As long as you review every day, you can remember these words." },
    ],
    questions: [
      { prompt: "___你需要，我___来帮忙。", translation: "As long as you need me, I will come help.", options: ["只要…就…", "只有…才…", "虽然…但是…", "因为…所以…"], answer: "只要…就…", explanation: "The condition is sufficient for the offer of help to follow." },
      { prompt: "___每天练习，你的中文___会提高。", translation: "As long as you practice every day, your Chinese will improve.", options: ["只要…就…", "不但…而且…", "越…越…", "除了…都…"], answer: "只要…就…", explanation: "只要 presents daily practice as enough to bring about improvement." },
      { prompt: "___有时间，我___给你打电话。", translation: "As long as I have time, I will call you.", options: ["只要…就…", "只有…才…", "一边…一边…", "虽然…可是…"], answer: "只要…就…", explanation: "Having time is the sufficient condition for making the call." },
    ],
  },
  {
    id: "hsk3-yibian",
    level: 3,
    category: "Complex sentence",
    title: "Simultaneous actions with 一边……一边……",
    pattern: "一边……一边……",
    summary: "Use 一边……一边…… for two ongoing actions performed at the same time.",
    structure: "Subject + 一边 + verb phrase 1, 一边 + verb phrase 2",
    note: "The two actions normally share a subject and can realistically happen together. Use it for simultaneous processes, not a sequence of completed events.",
    examples: [
      { zh: "我一边听音乐，一边做饭。", pinyin: "Wǒ yìbiān tīng yīnyuè, yìbiān zuòfàn.", en: "I cook while listening to music." },
      { zh: "她一边走路，一边打电话。", pinyin: "Tā yìbiān zǒulù, yìbiān dǎ diànhuà.", en: "She talks on the phone while walking." },
      { zh: "我们一边走路，一边说话。", pinyin: "Wǒmen yìbiān zǒulù, yìbiān shuōhuà.", en: "We talk while walking." },
    ],
    questions: [
      { prompt: "他___吃饭，___看新闻。", translation: "He watches the news while eating.", options: ["一边…一边…", "先…然后…", "不但…而且…", "越…越…"], answer: "一边…一边…", explanation: "The two ongoing actions happen at the same time." },
      { prompt: "她___听老师讲，___记笔记。", translation: "She takes notes while listening to the teacher.", options: ["一边…一边…", "因为…所以…", "只有…才…", "虽然…但是…"], answer: "一边…一边…", explanation: "Listening and taking notes are simultaneous actions with one subject." },
      { prompt: "我们___走路，___说话。", translation: "We talk while walking.", options: ["一边…一边…", "除了…以外…", "只要…就…", "先…再…"], answer: "一边…一边…", explanation: "一边 before each verb phrase links two actions happening together." },
    ],
  },
];
