"use strict";

window.GRAMMAR_LESSONS = [
  {
    id: "hsk1-shi",
    level: 1,
    category: "Sentence pattern",
    title: "Identifying with 是",
    pattern: "A 是 B",
    summary: "Use 是 to identify or classify a person or thing.",
    structure: "Noun or pronoun + 是 + noun or noun phrase",
    note: "Use 是 before a noun identity: 她是老师. With an adjective, normally say 她很忙 rather than 她是忙.",
    examples: [
      { zh: "她是老师。", pinyin: "Tā shì lǎoshī.", en: "She is a teacher." },
      { zh: "这是我的书。", pinyin: "Zhè shì wǒ de shū.", en: "This is my book." },
      { zh: "今天是星期五。", pinyin: "Jīntiān shì xīngqīwǔ.", en: "Today is Friday." },
    ],
    questions: [
      { prompt: "他___我的朋友。", translation: "He is my friend.", options: ["是", "有", "在", "很"], answer: "是", explanation: "是 connects 他 with the noun phrase 我的朋友." },
      { prompt: "明天___星期六。", translation: "Tomorrow is Saturday.", options: ["是", "会", "有", "比"], answer: "是", explanation: "Use 是 to identify a day or date." },
      { prompt: "这___北京大学。", translation: "This is Peking University.", options: ["是", "很", "没", "都"], answer: "是", explanation: "是 identifies what 这 refers to." },
    ],
  },
  {
    id: "hsk1-you",
    level: 1,
    category: "Sentence pattern",
    title: "Having and existing with 有",
    pattern: "A 有 B / Place 有 B",
    summary: "Use 有 for possession and for something existing in a place. Use 没有 to negate it.",
    structure: "Owner or place + 有 / 没有 + noun phrase",
    note: "Do not use 不有. The negative form is always 没有 or its short form 没.",
    examples: [
      { zh: "我有两个姐姐。", pinyin: "Wǒ yǒu liǎng ge jiějie.", en: "I have two older sisters." },
      { zh: "桌子上有一本书。", pinyin: "Zhuōzi shàng yǒu yì běn shū.", en: "There is a book on the table." },
      { zh: "今天没有课。", pinyin: "Jīntiān méiyǒu kè.", en: "There are no classes today." },
    ],
    questions: [
      { prompt: "我___一只猫。", translation: "I have a cat.", options: ["有", "是", "在", "会"], answer: "有", explanation: "有 expresses possession." },
      { prompt: "房间里___三把椅子。", translation: "There are three chairs in the room.", options: ["有", "是", "比", "想"], answer: "有", explanation: "Place + 有 introduces something that exists in that place." },
      { prompt: "他今天___时间。", translation: "He does not have time today.", options: ["没有", "不会", "不是", "不在"], answer: "没有", explanation: "The negative of 有 is 没有, never 不有." },
    ],
  },
  {
    id: "hsk1-de",
    level: 1,
    category: "Noun phrase",
    title: "Connecting descriptions with 的",
    pattern: "Description + 的 + noun",
    summary: "Use 的 to connect an owner or description to a noun.",
    structure: "Possessor, pronoun, or description + 的 + noun",
    note: "With close family relationships, 的 is often omitted: 我妈妈. Keep it when ownership or contrast needs emphasis.",
    examples: [
      { zh: "这是我的手机。", pinyin: "Zhè shì wǒ de shǒujī.", en: "This is my phone." },
      { zh: "穿红衣服的人是王老师。", pinyin: "Chuān hóng yīfu de rén shì Wáng lǎoshī.", en: "The person wearing red is Teacher Wang." },
      { zh: "我喜欢你买的茶。", pinyin: "Wǒ xǐhuan nǐ mǎi de chá.", en: "I like the tea you bought." },
    ],
    questions: [
      { prompt: "这是我___书。", translation: "This is my book.", options: ["的", "得", "地", "了"], answer: "的", explanation: "的 connects 我, the owner, to 书." },
      { prompt: "那个说汉语___人是谁？", translation: "Who is that person speaking Chinese?", options: ["的", "得", "在", "过"], answer: "的", explanation: "The phrase 说汉语 describes 人, so it is followed by 的." },
      { prompt: "我想买便宜___电脑。", translation: "I want to buy an inexpensive computer.", options: ["的", "得", "了", "吗"], answer: "的", explanation: "的 links the description 便宜 to the noun 电脑." },
    ],
  },
  {
    id: "hsk1-ma",
    level: 1,
    category: "Questions",
    title: "Yes-no questions with 吗",
    pattern: "Statement + 吗？",
    summary: "Turn a statement into a neutral yes-no question by adding 吗 at the end.",
    structure: "Subject + predicate + 吗？",
    note: "Do not add 吗 to a question that already uses a question word such as 谁, 什么, or 哪儿.",
    examples: [
      { zh: "你是学生吗？", pinyin: "Nǐ shì xuésheng ma?", en: "Are you a student?" },
      { zh: "你喜欢喝茶吗？", pinyin: "Nǐ xǐhuan hē chá ma?", en: "Do you like drinking tea?" },
      { zh: "他今天来吗？", pinyin: "Tā jīntiān lái ma?", en: "Is he coming today?" },
    ],
    questions: [
      { prompt: "你会说中文___？", translation: "Can you speak Chinese?", options: ["吗", "呢", "的", "了"], answer: "吗", explanation: "The sentence is a yes-no question, so 吗 goes at the end." },
      { prompt: "她是你的老师___？", translation: "Is she your teacher?", options: ["吗", "谁", "什么", "哪儿"], answer: "吗", explanation: "吗 turns the statement into a neutral yes-no question." },
      { prompt: "你明天有时间___？", translation: "Do you have time tomorrow?", options: ["吗", "怎么", "哪", "几"], answer: "吗", explanation: "There is no question word, so 吗 marks the yes-no question." },
    ],
  },
  {
    id: "hsk1-a-not-a",
    level: 1,
    category: "Questions",
    title: "Positive-negative questions",
    pattern: "A 不 A / 有没有",
    summary: "Repeat the predicate in positive and negative form to ask for a yes-no answer.",
    structure: "Subject + verb or adjective + 不 + verb or adjective？",
    note: "With 有, use 有没有. A positive-negative question normally does not also take 吗.",
    examples: [
      { zh: "你是不是老师？", pinyin: "Nǐ shì bu shì lǎoshī?", en: "Are you a teacher?" },
      { zh: "这个菜好不好吃？", pinyin: "Zhège cài hǎo bu hǎochī?", en: "Does this dish taste good?" },
      { zh: "你有没有哥哥？", pinyin: "Nǐ yǒu méiyǒu gēge?", en: "Do you have an older brother?" },
    ],
    questions: [
      { prompt: "你___想喝咖啡？", translation: "Do you want to drink coffee?", options: ["想不想", "是不是", "有没有", "会不会"], answer: "想不想", explanation: "The positive-negative form of 想 is 想不想." },
      { prompt: "他___学生？", translation: "Is he a student?", options: ["是不是", "有没有", "会不会", "好不好"], answer: "是不是", explanation: "The positive-negative form of 是 is 是不是." },
      { prompt: "你___时间？", translation: "Do you have time?", options: ["有没有", "是不是", "会不会", "想不想"], answer: "有没有", explanation: "有 uses the special positive-negative form 有没有." },
    ],
  },
  {
    id: "hsk1-progressive",
    level: 1,
    category: "Aspect",
    title: "Actions in progress",
    pattern: "在 / 正在 + verb (+ 呢)",
    summary: "Place 在, 正, or 正在 before a verb to show that an action is happening now.",
    structure: "Subject + 在 / 正在 + verb phrase + 呢",
    note: "呢 is optional when 在 or 正在 already marks the action as ongoing.",
    examples: [
      { zh: "我正在看书。", pinyin: "Wǒ zhèngzài kàn shū.", en: "I am reading." },
      { zh: "妈妈在做饭呢。", pinyin: "Māma zài zuò fàn ne.", en: "Mom is cooking." },
      { zh: "他们正上课呢。", pinyin: "Tāmen zhèng shàng kè ne.", en: "They are in class right now." },
    ],
    questions: [
      { prompt: "我___听音乐。", translation: "I am listening to music.", options: ["正在", "已经", "过", "比"], answer: "正在", explanation: "正在 before the verb marks an action happening now." },
      { prompt: "他在打电话___。", translation: "He is making a phone call.", options: ["呢", "吗", "的", "过"], answer: "呢", explanation: "呢 can reinforce that the action is currently in progress." },
      { prompt: "孩子们___睡觉。", translation: "The children are sleeping right now.", options: ["正", "已经", "常常", "一起"], answer: "正", explanation: "正 directly before the verb emphasizes 'right now.'" },
    ],
  },
  {
    id: "hsk1-bi",
    level: 1,
    category: "Comparison",
    title: "Comparing with 比",
    pattern: "A 比 B + adjective",
    summary: "Use 比 to say that A has more of a quality than B.",
    structure: "A + 比 + B + adjective",
    note: "Do not normally add 很 after 比. To say A is not as adjective as B, use A 没有 B + adjective.",
    examples: [
      { zh: "今天比昨天冷。", pinyin: "Jīntiān bǐ zuótiān lěng.", en: "Today is colder than yesterday." },
      { zh: "哥哥比我高。", pinyin: "Gēge bǐ wǒ gāo.", en: "My older brother is taller than me." },
      { zh: "这本书没有那本书贵。", pinyin: "Zhè běn shū méiyǒu nà běn shū guì.", en: "This book is not as expensive as that one." },
    ],
    questions: [
      { prompt: "上海___北京暖和。", translation: "Shanghai is warmer than Beijing.", options: ["比", "跟", "有", "在"], answer: "比", explanation: "比 introduces the standard being compared: 北京." },
      { prompt: "妹妹比我___。", translation: "My younger sister is younger than me.", options: ["小", "很小", "一样小", "没有小"], answer: "小", explanation: "The adjective follows the 比 phrase directly; 很 is not needed." },
      { prompt: "今天___昨天热。", translation: "Today is not as hot as yesterday.", options: ["没有", "不是", "不在", "还没"], answer: "没有", explanation: "A 没有 B + adjective means A is not as adjective as B." },
    ],
  },
  {
    id: "hsk1-le",
    level: 1,
    category: "Aspect",
    title: "Completed actions and new situations",
    pattern: "Verb + 了 / Sentence + 了",
    summary: "Use 了 after a verb for a completed action or at the end of a sentence for a new situation.",
    structure: "Subject + verb + 了 + object; or statement + 了",
    note: "Verb 了 focuses on completion. Sentence-final 了 signals that the situation has changed, as in 下雨了.",
    examples: [
      { zh: "我买了一本书。", pinyin: "Wǒ mǎi le yì běn shū.", en: "I bought a book." },
      { zh: "他回家了。", pinyin: "Tā huí jiā le.", en: "He went home." },
      { zh: "天气冷了。", pinyin: "Tiānqì lěng le.", en: "The weather has become cold." },
    ],
    questions: [
      { prompt: "昨天我看___一部电影。", translation: "Yesterday I watched a movie.", options: ["了", "着", "得", "的"], answer: "了", explanation: "了 after 看 marks the action as completed." },
      { prompt: "快十二点___。", translation: "It is almost twelve now.", options: ["了", "过", "着", "得"], answer: "了", explanation: "Sentence-final 了 marks a new situation: it is now nearly twelve." },
      { prompt: "雨停___，我们走吧。", translation: "The rain has stopped; let's go.", options: ["了", "得", "的", "在"], answer: "了", explanation: "了 shows that the situation has changed: the rain has stopped." },
    ],
  },
  {
    id: "hsk2-guo",
    level: 2,
    category: "Aspect",
    title: "Past experience with 过",
    pattern: "Verb + 过",
    summary: "Use 过 to say that an event has occurred at least once as part of someone's experience.",
    structure: "Subject + verb + 过 + object",
    note: "The negative is 没(有) + verb + 过. 过 presents experience, not simply one completed event.",
    examples: [
      { zh: "我去过上海。", pinyin: "Wǒ qù guo Shànghǎi.", en: "I have been to Shanghai." },
      { zh: "你吃过北京烤鸭吗？", pinyin: "Nǐ chī guo Běijīng kǎoyā ma?", en: "Have you eaten Peking duck?" },
      { zh: "她没看过这部电影。", pinyin: "Tā méi kàn guo zhè bù diànyǐng.", en: "She has not seen this movie." },
    ],
    questions: [
      { prompt: "我学___一点儿日语。", translation: "I have studied a little Japanese before.", options: ["过", "着", "得", "在"], answer: "过", explanation: "过 after 学 marks prior experience." },
      { prompt: "你去___长城吗？", translation: "Have you been to the Great Wall?", options: ["过", "着", "得", "的"], answer: "过", explanation: "去过 asks whether the visit is part of the listener's experience." },
      { prompt: "他___喝过咖啡。", translation: "He has never drunk coffee.", options: ["没", "不", "别", "不要"], answer: "没", explanation: "The negative pattern for experience is 没 + verb + 过." },
    ],
  },
  {
    id: "hsk2-zhe",
    level: 2,
    category: "Aspect",
    title: "Continuing states with 着",
    pattern: "Verb + 着",
    summary: "Use 着 after a verb to show that a state or action continues.",
    structure: "Subject + verb + 着 + object",
    note: "着 often describes a continuing posture or resulting state: 门开着. It differs from 正在, which foregrounds an action in progress.",
    examples: [
      { zh: "门开着。", pinyin: "Mén kāi zhe.", en: "The door is open." },
      { zh: "墙上挂着一张照片。", pinyin: "Qiáng shàng guà zhe yì zhāng zhàopiàn.", en: "A photograph is hanging on the wall." },
      { zh: "他笑着说话。", pinyin: "Tā xiào zhe shuōhuà.", en: "He speaks while smiling." },
    ],
    questions: [
      { prompt: "她手里拿___一本书。", translation: "She is holding a book in her hand.", options: ["着", "过", "得", "了"], answer: "着", explanation: "拿着 describes the continuing state of holding something." },
      { prompt: "窗户开___，有点儿冷。", translation: "The window is open, so it is a little cold.", options: ["着", "过", "在", "得"], answer: "着", explanation: "开着 describes the window's continuing open state." },
      { prompt: "他一直穿___一件蓝衣服。", translation: "He keeps wearing a blue item of clothing.", options: ["着", "过", "得", "在"], answer: "着", explanation: "穿着 describes a continuing state of wearing." },
    ],
  },
  {
    id: "hsk2-de-complement",
    level: 2,
    category: "Complement",
    title: "Describing performance with 得",
    pattern: "Verb + 得 + description",
    summary: "Use 得 after a verb to describe how well, quickly, or in what manner an action is performed.",
    structure: "Subject + verb + 得 + adjective or descriptive phrase",
    note: "When the verb has an object, the verb is commonly repeated: 她汉语说得很好 or 她说汉语说得很好.",
    examples: [
      { zh: "他说得很快。", pinyin: "Tā shuō de hěn kuài.", en: "He speaks very quickly." },
      { zh: "你写得真漂亮。", pinyin: "Nǐ xiě de zhēn piàoliang.", en: "You write beautifully." },
      { zh: "她汉语说得很好。", pinyin: "Tā Hànyǔ shuō de hěn hǎo.", en: "She speaks Chinese very well." },
    ],
    questions: [
      { prompt: "弟弟跑___很快。", translation: "My younger brother runs very fast.", options: ["得", "的", "地", "了"], answer: "得", explanation: "得 introduces the description 很快 after the verb 跑." },
      { prompt: "你唱___真好听。", translation: "You sing beautifully.", options: ["得", "的", "着", "过"], answer: "得", explanation: "得 connects the action 唱 with how it sounds." },
      { prompt: "他中文说___怎么样？", translation: "How well does he speak Chinese?", options: ["得", "的", "了", "在"], answer: "得", explanation: "Verb + 得 + 怎么样 asks about the manner or quality of an action." },
    ],
  },
  {
    id: "hsk2-shi-de",
    level: 2,
    category: "Emphasis",
    title: "Emphasizing details with 是……的",
    pattern: "是 + detail + verb + 的",
    summary: "Use 是……的 to emphasize when, where, how, or by whom a completed event happened.",
    structure: "Subject + 是 + emphasized detail + verb + 的",
    note: "This pattern discusses a known event and spotlights one detail; it is not the ordinary 是 sentence used for identity.",
    examples: [
      { zh: "我是昨天来的。", pinyin: "Wǒ shì zuótiān lái de.", en: "I came yesterday." },
      { zh: "这张照片是在北京拍的。", pinyin: "Zhè zhāng zhàopiàn shì zài Běijīng pāi de.", en: "This photograph was taken in Beijing." },
      { zh: "你是怎么知道的？", pinyin: "Nǐ shì zěnme zhīdào de?", en: "How did you find out?" },
    ],
    questions: [
      { prompt: "我___坐地铁来___。", translation: "I came by subway.", options: ["是…的", "正在…呢", "已经…了", "要…吗"], answer: "是…的", explanation: "是……的 emphasizes the means of travel, 坐地铁." },
      { prompt: "他___去年开始学中文___。", translation: "He started learning Chinese last year.", options: ["是…的", "正在…呢", "已经…了", "会…吗"], answer: "是…的", explanation: "是……的 emphasizes the time 去年." },
      { prompt: "这个蛋糕___妈妈做___。", translation: "Mom made this cake.", options: ["是…的", "在…呢", "有…吗", "比…了"], answer: "是…的", explanation: "是……的 emphasizes the person who performed the completed action." },
    ],
  },
  {
    id: "hsk2-yuelaiyue",
    level: 2,
    category: "Change",
    title: "Gradual change with 越来越",
    pattern: "越来越 + adjective / mental verb",
    summary: "Use 越来越 to show that a quality or state keeps increasing over time.",
    structure: "Subject + 越来越 + adjective or selected mental verb",
    note: "越来越 expresses change along one timeline. It differs from 越……越……, which links two changing conditions.",
    examples: [
      { zh: "天气越来越热了。", pinyin: "Tiānqì yuèláiyuè rè le.", en: "The weather is getting hotter and hotter." },
      { zh: "她的中文越来越好了。", pinyin: "Tā de Zhōngwén yuèláiyuè hǎo le.", en: "Her Chinese is getting better and better." },
      { zh: "我越来越喜欢这个城市。", pinyin: "Wǒ yuèláiyuè xǐhuan zhège chéngshì.", en: "I like this city more and more." },
    ],
    questions: [
      { prompt: "孩子___高了。", translation: "The child is getting taller and taller.", options: ["越来越", "已经很", "有一点", "还是很"], answer: "越来越", explanation: "越来越 marks a gradual increase in height over time." },
      { prompt: "这里的人___多。", translation: "There are more and more people here.", options: ["越来越", "非常", "特别", "不太"], answer: "越来越", explanation: "越来越多 means the number keeps increasing." },
      { prompt: "我___想家。", translation: "I miss home more and more.", options: ["越来越", "有一点", "常常", "不太"], answer: "越来越", explanation: "越来越 can modify a mental-state verb such as 想." },
    ],
  },
  {
    id: "hsk2-because",
    level: 2,
    category: "Complex sentence",
    title: "Cause and result",
    pattern: "因为……所以……",
    summary: "Use 因为 to introduce a reason and 所以 to introduce its result.",
    structure: "因为 + reason, 所以 + result",
    note: "In conversation, either 因为 or 所以 may be omitted when the relationship is already clear, but the full pair is useful for learning the logic.",
    examples: [
      { zh: "因为下雨，所以我们没出去。", pinyin: "Yīnwèi xiàyǔ, suǒyǐ wǒmen méi chūqu.", en: "Because it rained, we did not go out." },
      { zh: "因为他生病了，所以没来上课。", pinyin: "Yīnwèi tā shēngbìng le, suǒyǐ méi lái shàng kè.", en: "Because he was ill, he did not come to class." },
      { zh: "我很喜欢中文，所以每天都学习。", pinyin: "Wǒ hěn xǐhuan Zhōngwén, suǒyǐ měitiān dōu xuéxí.", en: "I like Chinese, so I study every day." },
    ],
    questions: [
      { prompt: "___今天很冷，___我穿了大衣。", translation: "Because it is cold today, I put on a coat.", options: ["因为…所以…", "虽然…但是…", "如果…就…", "一边…一边…"], answer: "因为…所以…", explanation: "The first clause gives the cause and the second gives its result." },
      { prompt: "___明天要考试，___他今晚不出去。", translation: "Because there is an exam tomorrow, he is not going out tonight.", options: ["因为…所以…", "虽然…但是…", "如果…就…", "只要…就…"], answer: "因为…所以…", explanation: "因为 introduces the reason; 所以 introduces the decision that follows." },
      { prompt: "___我没带钱，___不能买咖啡。", translation: "Because I did not bring money, I cannot buy coffee.", options: ["因为…所以…", "虽然…但是…", "如果…就…", "只要…就…"], answer: "因为…所以…", explanation: "The inability to buy coffee is the result of not bringing money." },
    ],
  },
  {
    id: "hsk2-although",
    level: 2,
    category: "Complex sentence",
    title: "Contrast with 虽然……但是……",
    pattern: "虽然……但是……",
    summary: "Use 虽然 to acknowledge one fact and 但是 to introduce a contrasting result.",
    structure: "虽然 + fact, 但是 + unexpected or contrasting fact",
    note: "可是 or 不过 can often replace 但是 in conversation.",
    examples: [
      { zh: "虽然下雨，但是我们还是去了。", pinyin: "Suīrán xiàyǔ, dànshì wǒmen háishi qù le.", en: "Although it rained, we still went." },
      { zh: "这件衣服虽然贵，但是很好看。", pinyin: "Zhè jiàn yīfu suīrán guì, dànshì hěn hǎokàn.", en: "Although this clothing is expensive, it looks very good." },
      { zh: "他虽然很累，但是还在工作。", pinyin: "Tā suīrán hěn lèi, dànshì hái zài gōngzuò.", en: "Although he is tired, he is still working." },
    ],
    questions: [
      { prompt: "___这本书很长，___很有意思。", translation: "Although this book is long, it is very interesting.", options: ["虽然…但是…", "因为…所以…", "如果…就…", "先…然后…"], answer: "虽然…但是…", explanation: "The second fact contrasts with what the first might lead us to expect." },
      { prompt: "___她感冒了，___她还是来上课了。", translation: "Although she has a cold, she still came to class.", options: ["虽然…但是…", "只要…就…", "一…就…", "又…又…"], answer: "虽然…但是…", explanation: "Coming to class contrasts with the fact that she has a cold." },
      { prompt: "___我不会做饭，___我想学。", translation: "Although I cannot cook, I want to learn.", options: ["虽然…但是…", "因为…所以…", "是…的", "越来越"], answer: "虽然…但是…", explanation: "虽然……但是…… presents two facts in contrast." },
    ],
  },
  {
    id: "hsk2-if",
    level: 2,
    category: "Complex sentence",
    title: "Conditions with 如果……就……",
    pattern: "如果……就……",
    summary: "Use 如果 to present a possible condition and 就 to introduce what follows from it.",
    structure: "如果 + condition, subject + 就 + result",
    note: "The subject of the result usually comes before 就: 如果你有时间，你就来吧.",
    examples: [
      { zh: "如果明天下雨，我们就不去。", pinyin: "Rúguǒ míngtiān xiàyǔ, wǒmen jiù bú qù.", en: "If it rains tomorrow, we will not go." },
      { zh: "如果你累了，就休息一下。", pinyin: "Rúguǒ nǐ lèi le, jiù xiūxi yíxià.", en: "If you are tired, take a short rest." },
      { zh: "如果有问题，就问老师。", pinyin: "Rúguǒ yǒu wèntí, jiù wèn lǎoshī.", en: "If you have a question, ask the teacher." },
    ],
    questions: [
      { prompt: "___你喜欢，___买吧。", translation: "If you like it, buy it.", options: ["如果…就…", "虽然…但是…", "因为…所以…", "一边…一边…"], answer: "如果…就…", explanation: "Liking it is the condition; buying it is the suggested result." },
      { prompt: "___他今天没空，我们___明天见。", translation: "If he is not free today, we will meet tomorrow.", options: ["如果…就…", "因为…所以…", "虽然…但是…", "只要…就…"], answer: "如果…就…", explanation: "如果 introduces a possible condition and 就 introduces the plan." },
      { prompt: "___你不懂，___告诉我。", translation: "If you do not understand, tell me.", options: ["如果…就…", "因为…所以…", "虽然…但是…", "只要…就…"], answer: "如果…就…", explanation: "The second clause tells what to do if the first condition is true." },
    ],
  },
];
