(() => {
  "use strict";

  const reader = (id, level, title, pinyinTitle, summary, minutes, sentences, vocabulary, questions) => ({
    id,
    level,
    title,
    pinyinTitle,
    summary,
    minutes,
    sentences,
    vocabulary,
    questions: questions.map((question, index) => ({ ...question, id: `${id}-q${index + 1}` })),
  });

  window.GRADED_READERS = [
    reader(
      "hsk1-new-neighbor",
      1,
      "新邻居",
      "Xīn línjū",
      "A new neighbor arrives and quickly feels at home.",
      3,
      [
        { zh: "今天，李明家旁边来了一个新邻居。", pinyin: "Jīntiān, Lǐ Míng jiā pángbiān lái le yí ge xīn línjū.", en: "Today, a new neighbor moved in next to Li Ming's home." },
        { zh: "她叫安娜，是一名学生。", pinyin: "Tā jiào Ānnà, shì yì míng xuésheng.", en: "Her name is Anna, and she is a student." },
        { zh: "安娜不会开门，因为她的手里有很多东西。", pinyin: "Ānnà bú huì kāi mén, yīnwèi tā de shǒu lǐ yǒu hěn duō dōngxi.", en: "Anna cannot open the door because she is carrying many things." },
        { zh: "李明看见了，就来帮她。", pinyin: "Lǐ Míng kànjiàn le, jiù lái bāng tā.", en: "Li Ming sees her and comes to help." },
        { zh: "安娜说：“谢谢！请来我家喝茶吧。”", pinyin: "Ānnà shuō: “Xièxie! Qǐng lái wǒ jiā hē chá ba.”", en: "Anna says, 'Thank you! Please come to my home for tea.'" },
        { zh: "晚上，他们一起喝茶，也成了好朋友。", pinyin: "Wǎnshang, tāmen yìqǐ hē chá, yě chéng le hǎo péngyou.", en: "That evening, they drink tea together and become good friends." },
      ],
      [
        { zh: "邻居", pinyin: "línjū", en: "neighbor" },
        { zh: "旁边", pinyin: "pángbiān", en: "beside" },
        { zh: "帮", pinyin: "bāng", en: "to help" },
        { zh: "一起", pinyin: "yìqǐ", en: "together" },
      ],
      [
        { prompt: "安娜是谁？", options: ["李明的老师", "李明的新邻居", "李明的姐姐"], answer: 1, explanation: "安娜刚搬到李明家旁边。" },
        { prompt: "为什么安娜不能开门？", options: ["她没有门", "她不在家", "她手里有很多东西"], answer: 2, explanation: "她拿着很多东西，所以不方便开门。" },
        { prompt: "晚上他们做了什么？", options: ["一起喝茶", "一起上课", "一起买东西"], answer: 0, explanation: "他们在安娜家一起喝茶。" },
      ],
    ),
    reader(
      "hsk1-weekend-breakfast",
      1,
      "周末的早饭",
      "Zhōumò de zǎofàn",
      "A family turns breakfast into a small weekend project.",
      3,
      [
        { zh: "星期六早上，爸爸起得很早。", pinyin: "Xīngqīliù zǎoshang, bàba qǐ de hěn zǎo.", en: "On Saturday morning, Dad gets up very early." },
        { zh: "他想给家人做早饭。", pinyin: "Tā xiǎng gěi jiārén zuò zǎofàn.", en: "He wants to make breakfast for the family." },
        { zh: "妈妈洗水果，女儿拿牛奶。", pinyin: "Māma xǐ shuǐguǒ, nǚ'ér ná niúnǎi.", en: "Mom washes fruit, and their daughter gets the milk." },
        { zh: "爸爸做了鸡蛋和面条。", pinyin: "Bàba zuò le jīdàn hé miàntiáo.", en: "Dad makes eggs and noodles." },
        { zh: "大家坐在桌子旁边吃早饭。", pinyin: "Dàjiā zuò zài zhuōzi pángbiān chī zǎofàn.", en: "Everyone sits by the table to eat breakfast." },
        { zh: "女儿说：“今天的早饭真好吃！”", pinyin: "Nǚ'ér shuō: “Jīntiān de zǎofàn zhēn hǎochī!”", en: "Their daughter says, 'Today's breakfast is really delicious!'" },
      ],
      [
        { zh: "周末", pinyin: "zhōumò", en: "weekend" },
        { zh: "早饭", pinyin: "zǎofàn", en: "breakfast" },
        { zh: "鸡蛋", pinyin: "jīdàn", en: "egg" },
        { zh: "好吃", pinyin: "hǎochī", en: "delicious" },
      ],
      [
        { prompt: "谁起得很早？", options: ["爸爸", "妈妈", "女儿"], answer: 0, explanation: "星期六早上爸爸先起床。" },
        { prompt: "女儿拿了什么？", options: ["水果", "牛奶", "面条"], answer: 1, explanation: "妈妈洗水果，女儿拿牛奶。" },
        { prompt: "女儿觉得早饭怎么样？", options: ["太少了", "不好吃", "很好吃"], answer: 2, explanation: "她说今天的早饭真好吃。" },
      ],
    ),
    reader(
      "hsk1-library-umbrella",
      1,
      "图书馆的伞",
      "Túshūguǎn de sǎn",
      "A rainy afternoon brings a simple act of kindness.",
      3,
      [
        { zh: "下午，小雨去图书馆看书。", pinyin: "Xiàwǔ, Xiǎoyǔ qù túshūguǎn kàn shū.", en: "In the afternoon, Xiaoyu goes to the library to read." },
        { zh: "她进去的时候，天气很好。", pinyin: "Tā jìnqù de shíhou, tiānqì hěn hǎo.", en: "When she goes in, the weather is good." },
        { zh: "两个小时以后，外面下雨了。", pinyin: "Liǎng ge xiǎoshí yǐhòu, wàimian xià yǔ le.", en: "Two hours later, it starts raining outside." },
        { zh: "小雨没有伞，只能在门口等。", pinyin: "Xiǎoyǔ méiyǒu sǎn, zhǐ néng zài ménkǒu děng.", en: "Xiaoyu has no umbrella, so she can only wait by the door." },
        { zh: "一位老师看见她，给了她一把伞。", pinyin: "Yí wèi lǎoshī kànjiàn tā, gěi le tā yì bǎ sǎn.", en: "A teacher sees her and gives her an umbrella." },
        { zh: "第二天，小雨把伞送回了图书馆。", pinyin: "Dì-èr tiān, Xiǎoyǔ bǎ sǎn sòng huí le túshūguǎn.", en: "The next day, Xiaoyu returns the umbrella to the library." },
      ],
      [
        { zh: "图书馆", pinyin: "túshūguǎn", en: "library" },
        { zh: "以后", pinyin: "yǐhòu", en: "after; later" },
        { zh: "门口", pinyin: "ménkǒu", en: "doorway" },
        { zh: "送回", pinyin: "sòng huí", en: "to return" },
      ],
      [
        { prompt: "小雨为什么在门口等？", options: ["图书馆关门了", "她没有伞", "她在等老师"], answer: 1, explanation: "外面下雨了，但是她没有伞。" },
        { prompt: "谁给了小雨一把伞？", options: ["一位老师", "她的妈妈", "一个学生"], answer: 0, explanation: "一位老师看见她并借给她伞。" },
        { prompt: "第二天小雨做了什么？", options: ["又去买书", "把伞送回去", "在家等雨"], answer: 1, explanation: "她把借来的伞送回图书馆。" },
      ],
    ),
    reader(
      "hsk1-mothers-gift",
      1,
      "给妈妈的礼物",
      "Gěi māma de lǐwù",
      "A child chooses a thoughtful birthday present.",
      3,
      [
        { zh: "明天是妈妈的生日。", pinyin: "Míngtiān shì māma de shēngrì.", en: "Tomorrow is Mom's birthday." },
        { zh: "小云想给妈妈买一个礼物。", pinyin: "Xiǎoyún xiǎng gěi māma mǎi yí ge lǐwù.", en: "Xiaoyun wants to buy Mom a gift." },
        { zh: "她先看了衣服，也看了书。", pinyin: "Tā xiān kàn le yīfu, yě kàn le shū.", en: "She first looks at clothes and also looks at books." },
        { zh: "妈妈很喜欢花，所以小云买了一些花。", pinyin: "Māma hěn xǐhuan huā, suǒyǐ Xiǎoyún mǎi le yìxiē huā.", en: "Mom really likes flowers, so Xiaoyun buys some." },
        { zh: "她还写了一张小卡片。", pinyin: "Tā hái xiě le yì zhāng xiǎo kǎpiàn.", en: "She also writes a small card." },
        { zh: "妈妈收到礼物以后，非常高兴。", pinyin: "Māma shōudào lǐwù yǐhòu, fēicháng gāoxìng.", en: "Mom is very happy after receiving the gift." },
      ],
      [
        { zh: "生日", pinyin: "shēngrì", en: "birthday" },
        { zh: "礼物", pinyin: "lǐwù", en: "gift" },
        { zh: "花", pinyin: "huā", en: "flower" },
        { zh: "收到", pinyin: "shōudào", en: "to receive" },
      ],
      [
        { prompt: "明天是什么日子？", options: ["小云的生日", "妈妈的生日", "爸爸的生日"], answer: 1, explanation: "故事一开始说，明天是妈妈的生日。" },
        { prompt: "小云最后买了什么？", options: ["花", "衣服", "一本书"], answer: 0, explanation: "因为妈妈喜欢花，小云买了花。" },
        { prompt: "妈妈收到礼物以后怎么样？", options: ["很累", "很高兴", "很忙"], answer: 1, explanation: "妈妈收到礼物以后非常高兴。" },
      ],
    ),
    reader(
      "hsk2-missed-bus",
      2,
      "错过的公交车",
      "Cuòguò de gōngjiāochē",
      "A missed bus changes a rushed morning for the better.",
      4,
      [
        { zh: "今天早上，陈伟起晚了十分钟。", pinyin: "Jīntiān zǎoshang, Chén Wěi qǐ wǎn le shí fēnzhōng.", en: "This morning, Chen Wei gets up ten minutes late." },
        { zh: "他没吃早饭，就跑到了车站。", pinyin: "Tā méi chī zǎofàn, jiù pǎo dào le chēzhàn.", en: "Without eating breakfast, he runs to the bus stop." },
        { zh: "可是，他刚到车站，公交车就开走了。", pinyin: "Kěshì, tā gāng dào chēzhàn, gōngjiāochē jiù kāi zǒu le.", en: "But just as he reaches the stop, the bus drives away." },
        { zh: "下一辆车要二十分钟以后才来。", pinyin: "Xià yí liàng chē yào èrshí fēnzhōng yǐhòu cái lái.", en: "The next bus will not arrive for twenty minutes." },
        { zh: "陈伟在旁边的小店买了面包和牛奶。", pinyin: "Chén Wěi zài pángbiān de xiǎodiàn mǎi le miànbāo hé niúnǎi.", en: "Chen Wei buys bread and milk at a nearby shop." },
        { zh: "他坐在车站吃完早饭，心里也不着急了。", pinyin: "Tā zuò zài chēzhàn chī wán zǎofàn, xīnli yě bù zháojí le.", en: "He finishes breakfast at the stop and no longer feels rushed." },
        { zh: "虽然他迟到了，但是这次他没有空着肚子上班。", pinyin: "Suīrán tā chídào le, dànshì zhè cì tā méiyǒu kōngzhe dùzi shàngbān.", en: "Although he is late, this time he does not go to work on an empty stomach." },
      ],
      [
        { zh: "错过", pinyin: "cuòguò", en: "to miss" },
        { zh: "车站", pinyin: "chēzhàn", en: "station; stop" },
        { zh: "开走", pinyin: "kāi zǒu", en: "to drive away" },
        { zh: "着急", pinyin: "zháojí", en: "anxious; rushed" },
        { zh: "迟到", pinyin: "chídào", en: "to be late" },
      ],
      [
        { prompt: "陈伟为什么错过了公交车？", options: ["他起晚了", "公交车来早了", "他找不到车站"], answer: 0, explanation: "他比平时晚起了十分钟。" },
        { prompt: "下一辆车什么时候来？", options: ["十分钟以后", "二十分钟以后", "三十分钟以后"], answer: 1, explanation: "故事说下一辆车要二十分钟以后才来。" },
        { prompt: "等车的时候陈伟做了什么？", options: ["给公司打电话", "回家睡觉", "买了早饭"], answer: 2, explanation: "他在旁边的小店买了面包和牛奶。" },
      ],
    ),
    reader(
      "hsk2-new-colleague",
      2,
      "新同事的第一天",
      "Xīn tóngshì de dì-yī tiān",
      "A small welcome helps a new colleague settle in.",
      4,
      [
        { zh: "星期一，公司来了一位新同事，她叫周兰。", pinyin: "Xīngqīyī, gōngsī lái le yí wèi xīn tóngshì, tā jiào Zhōu Lán.", en: "On Monday, a new colleague named Zhou Lan joins the company." },
        { zh: "周兰第一次来这个城市，对附近不太了解。", pinyin: "Zhōu Lán dì-yī cì lái zhège chéngshì, duì fùjìn bú tài liǎojiě.", en: "It is Zhou Lan's first time in the city, and she does not know the area well." },
        { zh: "中午，大家带她去公司后面的一家饭店。", pinyin: "Zhōngwǔ, dàjiā dài tā qù gōngsī hòumian de yì jiā fàndiàn.", en: "At noon, everyone takes her to a restaurant behind the office." },
        { zh: "同事们介绍了这里的交通、商店和公园。", pinyin: "Tóngshìmen jièshào le zhèlǐ de jiāotōng, shāngdiàn hé gōngyuán.", en: "Her colleagues explain the local transport, shops, and parks." },
        { zh: "下午，经理又教她使用公司的电脑系统。", pinyin: "Xiàwǔ, jīnglǐ yòu jiāo tā shǐyòng gōngsī de diànnǎo xìtǒng.", en: "In the afternoon, the manager teaches her to use the company's computer system." },
        { zh: "下班的时候，周兰已经记住了很多人的名字。", pinyin: "Xiàbān de shíhou, Zhōu Lán yǐjīng jìzhù le hěn duō rén de míngzi.", en: "By the end of the day, Zhou Lan has remembered many people's names." },
        { zh: "她觉得第一天虽然很忙，但是也很温暖。", pinyin: "Tā juéde dì-yī tiān suīrán hěn máng, dànshì yě hěn wēnnuǎn.", en: "She feels that although her first day was busy, it was also warm and welcoming." },
      ],
      [
        { zh: "同事", pinyin: "tóngshì", en: "colleague" },
        { zh: "附近", pinyin: "fùjìn", en: "nearby" },
        { zh: "了解", pinyin: "liǎojiě", en: "to understand" },
        { zh: "系统", pinyin: "xìtǒng", en: "system" },
        { zh: "记住", pinyin: "jìzhù", en: "to remember" },
        { zh: "温暖", pinyin: "wēnnuǎn", en: "warm" },
      ],
      [
        { prompt: "周兰对什么不太了解？", options: ["公司的工作", "城市附近的情况", "同事的名字"], answer: 1, explanation: "她第一次来这个城市，不熟悉附近。" },
        { prompt: "经理下午教周兰什么？", options: ["使用电脑系统", "坐公交车", "介绍新同事"], answer: 0, explanation: "经理教她使用公司的电脑系统。" },
        { prompt: "周兰觉得第一天怎么样？", options: ["很轻松，但是无聊", "很忙，但是温暖", "很难，也很冷"], answer: 1, explanation: "她觉得忙碌中也感受到了同事的温暖。" },
      ],
    ),
    reader(
      "hsk2-weekend-hike",
      2,
      "没看到的日出",
      "Méi kàndào de rìchū",
      "Friends learn that a trip can still be worthwhile when plans change.",
      4,
      [
        { zh: "小林和朋友决定周日早上去山上看日出。", pinyin: "Xiǎo Lín hé péngyou juédìng Zhōurì zǎoshang qù shān shàng kàn rìchū.", en: "Xiaolin and a friend decide to watch the sunrise from a mountain on Sunday." },
        { zh: "他们五点出发，走了一个多小时。", pinyin: "Tāmen wǔ diǎn chūfā, zǒu le yí ge duō xiǎoshí.", en: "They set out at five and walk for more than an hour." },
        { zh: "快到山顶的时候，天上突然有了很多云。", pinyin: "Kuài dào shāndǐng de shíhou, tiānshang tūrán yǒu le hěn duō yún.", en: "As they near the summit, many clouds suddenly appear." },
        { zh: "他们没有看到太阳，只看见了一片白色。", pinyin: "Tāmen méiyǒu kàndào tàiyáng, zhǐ kànjiàn le yí piàn báisè.", en: "They do not see the sun, only a field of white." },
        { zh: "朋友有点儿失望，小林却拿出了热茶和蛋糕。", pinyin: "Péngyou yǒudiǎnr shīwàng, Xiǎo Lín què ná chū le rè chá hé dàngāo.", en: "The friend is disappointed, but Xiaolin brings out hot tea and cake." },
        { zh: "两个人坐在云里吃东西，觉得非常安静。", pinyin: "Liǎng ge rén zuò zài yún lǐ chī dōngxi, juéde fēicháng ānjìng.", en: "They sit among the clouds and eat, enjoying the quiet." },
        { zh: "下山时，他们都说下次还要再来。", pinyin: "Xià shān shí, tāmen dōu shuō xià cì hái yào zài lái.", en: "On the way down, they both say they will return." },
      ],
      [
        { zh: "日出", pinyin: "rìchū", en: "sunrise" },
        { zh: "山顶", pinyin: "shāndǐng", en: "mountaintop" },
        { zh: "突然", pinyin: "tūrán", en: "suddenly" },
        { zh: "失望", pinyin: "shīwàng", en: "disappointed" },
        { zh: "安静", pinyin: "ānjìng", en: "quiet" },
      ],
      [
        { prompt: "他们为什么没看到日出？", options: ["出发太晚", "天上有很多云", "走错了路"], answer: 1, explanation: "快到山顶时云变多，挡住了太阳。" },
        { prompt: "小林带了什么？", options: ["热茶和蛋糕", "咖啡和面包", "水果和牛奶"], answer: 0, explanation: "小林拿出了热茶和蛋糕。" },
        { prompt: "下山时他们决定什么？", options: ["以后不爬山", "下次再来", "马上回家睡觉"], answer: 1, explanation: "虽然没看到日出，他们还是想再来。" },
      ],
    ),
    reader(
      "hsk2-small-restaurant",
      2,
      "只有三张桌子的饭店",
      "Zhǐ yǒu sān zhāng zhuōzi de fàndiàn",
      "A tiny restaurant earns loyal customers through care and consistency.",
      4,
      [
        { zh: "我家附近有一家很小的饭店，里面只有三张桌子。", pinyin: "Wǒ jiā fùjìn yǒu yì jiā hěn xiǎo de fàndiàn, lǐmiàn zhǐ yǒu sān zhāng zhuōzi.", en: "Near my home is a tiny restaurant with only three tables." },
        { zh: "老板每天早上去市场买新鲜的菜。", pinyin: "Lǎobǎn měitiān zǎoshang qù shìchǎng mǎi xīnxiān de cài.", en: "Every morning, the owner buys fresh ingredients at the market." },
        { zh: "菜单上的菜不多，但是每一道都做得很认真。", pinyin: "Càidān shàng de cài bù duō, dànshì měi yí dào dōu zuò de hěn rènzhēn.", en: "The menu is short, but every dish is prepared carefully." },
        { zh: "客人来的时候，老板常常记得他们喜欢吃什么。", pinyin: "Kèrén lái de shíhou, lǎobǎn chángcháng jìde tāmen xǐhuan chī shénme.", en: "When customers arrive, the owner often remembers what they like." },
        { zh: "有一次我感冒了，他还给我做了一碗清淡的面。", pinyin: "Yǒu yí cì wǒ gǎnmào le, tā hái gěi wǒ zuò le yì wǎn qīngdàn de miàn.", en: "Once when I had a cold, he made me a bowl of light noodles." },
        { zh: "所以，饭店虽然小，每天还是有很多人来。", pinyin: "Suǒyǐ, fàndiàn suīrán xiǎo, měitiān háishi yǒu hěn duō rén lái.", en: "So although the restaurant is small, many people still come each day." },
      ],
      [
        { zh: "市场", pinyin: "shìchǎng", en: "market" },
        { zh: "新鲜", pinyin: "xīnxiān", en: "fresh" },
        { zh: "菜单", pinyin: "càidān", en: "menu" },
        { zh: "客人", pinyin: "kèrén", en: "customer; guest" },
        { zh: "清淡", pinyin: "qīngdàn", en: "light in flavor" },
      ],
      [
        { prompt: "老板每天早上做什么？", options: ["去市场买菜", "换新的桌子", "给客人打电话"], answer: 0, explanation: "他每天早上去市场买新鲜的菜。" },
        { prompt: "老板为什么给“我”做清淡的面？", options: ["我不喜欢吃菜", "我感冒了", "饭店没有别的菜"], answer: 1, explanation: "因为“我”感冒了，清淡的面更合适。" },
        { prompt: "饭店为什么有很多客人？", options: ["地方特别大", "菜便宜到免费", "老板做菜认真，也关心客人"], answer: 2, explanation: "认真做菜和记住客人的喜好让大家愿意再来。" },
      ],
    ),
    reader(
      "hsk3-community-garden",
      3,
      "楼下的小花园",
      "Lóuxià de xiǎo huāyuán",
      "Neighbors transform an unused corner into a shared garden.",
      5,
      [
        { zh: "我们楼下原来有一块空地，大家平时只在那里放旧自行车。", pinyin: "Wǒmen lóuxià yuánlái yǒu yí kuài kòngdì, dàjiā píngshí zhǐ zài nàli fàng jiù zìxíngchē.", en: "There used to be an empty space downstairs where people only left old bicycles." },
        { zh: "去年春天，一位退休的邻居建议把它变成小花园。", pinyin: "Qùnián chūntiān, yí wèi tuìxiū de línjū jiànyì bǎ tā biàn chéng xiǎo huāyuán.", en: "Last spring, a retired neighbor suggested turning it into a small garden." },
        { zh: "开始时，有些人担心没有人愿意长期照顾。", pinyin: "Kāishǐ shí, yǒuxiē rén dānxīn méiyǒu rén yuànyì chángqī zhàogù.", en: "At first, some people worried no one would care for it long-term." },
        { zh: "后来，大家决定每个家庭每月负责一天。", pinyin: "Hòulái, dàjiā juédìng měi ge jiātíng měi yuè fùzé yì tiān.", en: "Later, everyone decided each family would take responsibility one day a month." },
        { zh: "孩子们种花，老人们种菜，年轻人修好了旁边的椅子。", pinyin: "Háizimen zhòng huā, lǎorénmen zhòng cài, niánqīngrén xiū hǎo le pángbiān de yǐzi.", en: "Children planted flowers, older residents planted vegetables, and younger people repaired the bench." },
        { zh: "现在天气好的时候，邻居们常常坐在那里聊天。", pinyin: "Xiànzài tiānqì hǎo de shíhou, línjūmen chángcháng zuò zài nàli liáotiān.", en: "Now, when the weather is good, neighbors often sit there and chat." },
        { zh: "这块不大的地方，让住在同一栋楼里的人真正认识了彼此。", pinyin: "Zhè kuài bú dà de dìfang, ràng zhù zài tóng yí dòng lóu lǐ de rén zhēnzhèng rènshi le bǐcǐ.", en: "This small place helped people in the same building truly get to know one another." },
      ],
      [
        { zh: "空地", pinyin: "kòngdì", en: "empty lot" },
        { zh: "退休", pinyin: "tuìxiū", en: "to retire" },
        { zh: "建议", pinyin: "jiànyì", en: "to suggest" },
        { zh: "长期", pinyin: "chángqī", en: "long-term" },
        { zh: "负责", pinyin: "fùzé", en: "to be responsible for" },
        { zh: "彼此", pinyin: "bǐcǐ", en: "one another" },
      ],
      [
        { prompt: "空地原来是做什么用的？", options: ["停放旧自行车", "种花和种菜", "让孩子们运动"], answer: 0, explanation: "改造以前，大家只在那里放旧自行车。" },
        { prompt: "大家怎样解决长期照顾的问题？", options: ["请公司管理", "每个家庭每月负责一天", "只让退休邻居负责"], answer: 1, explanation: "轮流负责让花园可以长期被照顾。" },
        { prompt: "花园带来的最大变化是什么？", options: ["房子变贵了", "大家认识了彼此", "自行车更多了"], answer: 1, explanation: "结尾强调邻居们因为花园真正认识了彼此。" },
      ],
    ),
    reader(
      "hsk3-museum-volunteer",
      3,
      "博物馆的第一个问题",
      "Bówùguǎn de dì-yī ge wèntí",
      "A volunteer learns that useful explanations begin with listening.",
      5,
      [
        { zh: "大学放暑假后，林雪报名当市博物馆的志愿者。", pinyin: "Dàxué fàng shǔjià hòu, Lín Xuě bàomíng dāng shì bówùguǎn de zhìyuànzhě.", en: "After university breaks for summer, Lin Xue volunteers at the city museum." },
        { zh: "培训时，老师告诉她，不但要记住展品的历史，还要学会观察游客。", pinyin: "Péixùn shí, lǎoshī gàosu tā, bùdàn yào jìzhù zhǎnpǐn de lìshǐ, hái yào xuéhuì guānchá yóukè.", en: "During training, the instructor says she must learn the exhibits' history and observe visitors." },
        { zh: "第一天，一位老人站在一张旧照片前看了很久。", pinyin: "Dì-yī tiān, yí wèi lǎorén zhàn zài yì zhāng jiù zhàopiàn qián kàn le hěn jiǔ.", en: "On her first day, an older man studies an old photograph for a long time." },
        { zh: "林雪准备介绍照片时，老人却先问：“你知道这条街现在叫什么吗？”", pinyin: "Lín Xuě zhǔnbèi jièshào zhàopiàn shí, lǎorén què xiān wèn: “Nǐ zhīdào zhè tiáo jiē xiànzài jiào shénme ma?”", en: "As Lin Xue prepares to explain it, he asks what the street is called now." },
        { zh: "原来，老人小时候就住在那里，他知道很多照片外的故事。", pinyin: "Yuánlái, lǎorén xiǎoshíhou jiù zhù zài nàli, tā zhīdào hěn duō zhàopiàn wài de gùshi.", en: "It turns out he lived there as a child and knows many stories beyond the photograph." },
        { zh: "林雪认真听完，把几个故事记在了本子上。", pinyin: "Lín Xuě rènzhēn tīng wán, bǎ jǐ ge gùshi jì zài le běnzi shàng.", en: "Lin Xue listens carefully and writes several stories in her notebook." },
        { zh: "从那以后，她给游客介绍展品以前，总会先问他们从哪里来。", pinyin: "Cóng nà yǐhòu, tā gěi yóukè jièshào zhǎnpǐn yǐqián, zǒng huì xiān wèn tāmen cóng nǎli lái.", en: "After that, before explaining an exhibit, she first asks visitors where they come from." },
      ],
      [
        { zh: "志愿者", pinyin: "zhìyuànzhě", en: "volunteer" },
        { zh: "培训", pinyin: "péixùn", en: "training" },
        { zh: "展品", pinyin: "zhǎnpǐn", en: "exhibit" },
        { zh: "观察", pinyin: "guānchá", en: "to observe" },
        { zh: "原来", pinyin: "yuánlái", en: "as it turns out" },
      ],
      [
        { prompt: "培训老师要求林雪学会什么？", options: ["修理展品", "观察游客", "给老人拍照"], answer: 1, explanation: "除了展品历史，她还要学会观察游客。" },
        { prompt: "老人为什么知道照片外的故事？", options: ["他小时候住在那里", "他是博物馆老师", "他拍了那张照片"], answer: 0, explanation: "那条街是老人小时候生活的地方。" },
        { prompt: "这次经历以后，林雪改变了什么？", options: ["不再介绍展品", "先了解游客，再开始介绍", "只接待老年游客"], answer: 1, explanation: "她学会先听游客的背景和经历。" },
      ],
    ),
    reader(
      "hsk3-lost-wallet",
      3,
      "绕了一圈的钱包",
      "Rào le yì quān de qiánbāo",
      "A lost wallet reveals an unexpected chain of helpful strangers.",
      5,
      [
        { zh: "下班回家以后，赵凯发现钱包不见了。", pinyin: "Xiàbān huí jiā yǐhòu, Zhào Kǎi fāxiàn qiánbāo bú jiàn le.", en: "After returning home from work, Zhao Kai discovers his wallet is missing." },
        { zh: "他回想了一下，觉得可能落在了出租车上。", pinyin: "Tā huíxiǎng le yíxià, juéde kěnéng là zài le chūzūchē shàng.", en: "Thinking back, he believes he may have left it in the taxi." },
        { zh: "因为没有记住车牌号，他只好给出租车公司打电话。", pinyin: "Yīnwèi méiyǒu jìzhù chēpái hào, tā zhǐhǎo gěi chūzūchē gōngsī dǎ diànhuà.", en: "Because he did not note the license plate, he calls the taxi company." },
        { zh: "客服查了半天，还是没有找到那位司机。", pinyin: "Kèfú chá le bàntiān, háishi méiyǒu zhǎodào nà wèi sījī.", en: "Customer service searches for a while but cannot find the driver." },
        { zh: "第二天早上，赵凯却接到了附近派出所的电话。", pinyin: "Dì-èr tiān zǎoshang, Zhào Kǎi què jiēdào le fùjìn pàichūsuǒ de diànhuà.", en: "The next morning, Zhao Kai receives a call from the nearby police station." },
        { zh: "原来，一位乘客在出租车后座发现钱包，把它交给了司机。", pinyin: "Yuánlái, yí wèi chéngkè zài chūzūchē hòuzuò fāxiàn qiánbāo, bǎ tā jiāo gěi le sījī.", en: "A passenger had found the wallet in the back seat and given it to the driver." },
        { zh: "司机下班后又把钱包送到了派出所，里面的东西一样也没少。", pinyin: "Sījī xiàbān hòu yòu bǎ qiánbāo sòng dào le pàichūsuǒ, lǐmiàn de dōngxi yí yàng yě méi shǎo.", en: "After work, the driver took it to the police station, with nothing missing." },
      ],
      [
        { zh: "回想", pinyin: "huíxiǎng", en: "to recall" },
        { zh: "落在", pinyin: "là zài", en: "to leave behind" },
        { zh: "车牌号", pinyin: "chēpái hào", en: "license plate number" },
        { zh: "客服", pinyin: "kèfú", en: "customer service" },
        { zh: "派出所", pinyin: "pàichūsuǒ", en: "police station" },
        { zh: "乘客", pinyin: "chéngkè", en: "passenger" },
      ],
      [
        { prompt: "赵凯开始认为钱包在哪里？", options: ["公司里", "出租车上", "派出所"], answer: 1, explanation: "他回想后觉得钱包可能落在出租车上。" },
        { prompt: "谁最先发现了钱包？", options: ["另一位乘客", "出租车客服", "派出所工作人员"], answer: 0, explanation: "另一位乘客在出租车后座发现了它。" },
        { prompt: "钱包最后是怎样到派出所的？", options: ["赵凯自己送去的", "乘客直接送去的", "司机下班后送去的"], answer: 2, explanation: "乘客交给司机，司机再把钱包送到派出所。" },
      ],
    ),
    reader(
      "hsk3-learning-to-cook",
      3,
      "一张没有写完的菜谱",
      "Yì zhāng méiyǒu xiě wán de càipǔ",
      "An unfinished recipe teaches someone to cook by paying attention.",
      5,
      [
        { zh: "奶奶搬家时，给我留下了一本很旧的菜谱。", pinyin: "Nǎinai bānjiā shí, gěi wǒ liúxià le yì běn hěn jiù de càipǔ.", en: "When Grandma moved, she left me an old recipe book." },
        { zh: "书里写着各种家常菜的做法，不过很多地方只有几个简单的词。", pinyin: "Shū lǐ xiězhe gè zhǒng jiācháng cài de zuòfǎ, búguò hěn duō dìfang zhǐ yǒu jǐ ge jiǎndān de cí.", en: "It contains home-style recipes, but many parts have only a few simple words." },
        { zh: "比如，一道汤只写了“少放盐，慢慢等”。", pinyin: "Bǐrú, yí dào tāng zhǐ xiě le “shǎo fàng yán, mànmàn děng”.", en: "For example, one soup recipe says only, 'Use less salt and wait slowly.'" },
        { zh: "我第一次做的时候，按照普通菜谱的时间关了火，味道却不够好。", pinyin: "Wǒ dì-yī cì zuò de shíhou, ànzhào pǔtōng càipǔ de shíjiān guān le huǒ, wèidào què bú gòu hǎo.", en: "The first time, I turned off the heat according to a normal recipe, but the flavor was weak." },
        { zh: "第二次，我没有看钟，而是注意汤的颜色和香味。", pinyin: "Dì-èr cì, wǒ méiyǒu kàn zhōng, érshì zhùyì tāng de yánsè hé xiāngwèi.", en: "The second time, I watched the soup's color and aroma instead of the clock." },
        { zh: "当厨房里出现小时候熟悉的味道时，我才关火。", pinyin: "Dāng chúfáng lǐ chūxiàn xiǎoshíhou shúxī de wèidào shí, wǒ cái guān huǒ.", en: "I turned off the heat only when the kitchen smelled familiar from childhood." },
        { zh: "那时我明白了，奶奶没有写下来的部分，需要做饭的人自己去发现。", pinyin: "Nà shí wǒ míngbai le, nǎinai méiyǒu xiě xiàlai de bùfen, xūyào zuòfàn de rén zìjǐ qù fāxiàn.", en: "Then I understood that the unwritten parts had to be discovered by the cook." },
      ],
      [
        { zh: "菜谱", pinyin: "càipǔ", en: "recipe" },
        { zh: "家常菜", pinyin: "jiācháng cài", en: "home-style dish" },
        { zh: "按照", pinyin: "ànzhào", en: "according to" },
        { zh: "味道", pinyin: "wèidào", en: "flavor; smell" },
        { zh: "香味", pinyin: "xiāngwèi", en: "aroma" },
        { zh: "熟悉", pinyin: "shúxī", en: "familiar" },
      ],
      [
        { prompt: "奶奶的菜谱有什么特别？", options: ["很多地方写得很简单", "只写甜点的做法", "每道菜都有照片"], answer: 0, explanation: "很多步骤只留下几个简单的词。" },
        { prompt: "第二次做汤时，“我”注意什么？", options: ["普通菜谱的时间", "汤的颜色和香味", "奶奶打来的电话"], answer: 1, explanation: "“我”不再只看时间，而是观察汤本身。" },
        { prompt: "“我”最后明白了什么？", options: ["菜谱完全没有用", "做饭只需要等待", "有些经验需要自己观察和发现"], answer: 2, explanation: "奶奶没写出的经验，需要做饭的人通过观察发现。" },
      ],
    ),
  ];
})();
